Repository reactor/reactor-core, pull requests merged in 2018-04, with the labels that each got.

#1129 fix #1125 Add TTL-generator variant to Mono.cache
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheTime.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheTimeTest.java
Labels: enhancement

#1154 fix #1131 Add Mono.fromFuture/fromCompletionStage Supplier variants
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/MonoTests.java
Labels: enhancement

#1159 fix #1158 Flux.take(0) now eagerly cancels on subscription
  reactor-core/src/main/java/reactor/core/publisher/FluxTake.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTakeTest.java
Labels: consider backport, enhancement

#1163 javadoc fixes
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: documentation
