Repository reactor/reactor-core, pull requests merged in 2018-05, with the labels that each got.

#1188 [doc] Point to reference doc operator matrix in Flux/Mono javadoc
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: documentation

#1195 fix issue with generified BiConsumer
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/test/java/reactor/core/publisher/OnNextFailureStrategyTest.java
Labels: enhancement

#1141 fix #437 Add simplified implementation for Mono.publish(Function)
  reactor-core/src/main/java/reactor/core/publisher/FluxPublishMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/MonoPublishMulticast.java
  reactor-core/src/test/java/reactor/core/publisher/MonoPublishMulticastTest.java
Labels: enhancement

#1197 fix #1194 Request is not accounted for in FluxOnBackpressureBufferTimout
  reactor-core/src/main/java/reactor/core/publisher/FluxOnBackpressureBufferTimeout.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureBufferTimeoutTest.java
Labels: bug, need-backport-3.1

#1199 [doc] Remove misleading Context propagation implementation note
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: documentation, enhancement

#1042 fix #1033 Remove empty windows from windowUntil/While
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowPredicate.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowPredicateTest.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
  src/docs/asciidoc/advancedFeatures.adoc
Labels: API change, enhancement

#1178 Unexpected behavior for Flux.interval when scheduled interval does not supported
  reactor-core/src/main/java/reactor/core/scheduler/InstantPeriodicWorkerTask.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/test/java/reactor/core/publisher/FluxIntervalTest.java
  reactor-core/src/test/java/reactor/core/scheduler/InstantPeriodicWorkerTaskTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
Labels: bug, need-backport-3.1

#1207 fix #1204 Lift properly maintain GroupedFlux/ConnectableFlux interface
  reactor-core/src/main/java/reactor/core/publisher/ConnectableLift.java
  reactor-core/src/main/java/reactor/core/publisher/GroupedLift.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/LiftFunctionTest.java
Labels: need-backport-3.1

#1209 #1149 fix in javadoc
  reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  src/docs/marble/directprocessorerror.png
  src/docs/marble/directprocessornormal.png
  src/docs/marble/directprocessorterminal.png
  src/docs/marble/unicastprocessornormal.png
  src/docs/marble/unicastprocessoroverflow.png
  src/docs/marble/unicastprocessorterminal.png
Labels: documentation

#1213 fix #1192 Revert bad replace of word "set" with "push" in comments
  reactor-core/src/main/java/reactor/core/Disposable.java
  reactor-core/src/main/java/reactor/core/Disposables.java
  reactor-core/src/main/java/reactor/core/Exceptions.java
  reactor-core/src/main/java/reactor/core/Scannable.java
  reactor-core/src/main/java/reactor/core/publisher/BaseSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFirstEmitting.java
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFirst.java
  reactor-core/src/main/java/reactor/core/publisher/MonoIgnoreThen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java
  reactor-core/src/main/java/reactor/core/publisher/OperatorDisposables.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/main/java/reactor/core/publisher/ReplayProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/RingBuffer.java
  reactor-core/src/main/java/reactor/core/publisher/TopicProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/WorkQueueProcessor.java
  reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCombineLatestTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxSpecTests.java
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
  reactor-core/src/test/java/reactor/test/subscriber/AssertSubscriber.java
  reactor-test/src/main/java/reactor/test/StepVerifier.java
  reactor-test/src/main/java/reactor/test/StepVerifierOptions.java
  reactor-test/src/main/java/reactor/test/publisher/TestPublisher.java
  reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: bug, documentation, need-backport-3.1

#1183 Add #1123 metrics to `Flux`
  build.gradle
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxMetrics.java
  reactor-core/src/main/java/reactor/core/publisher/FluxMetricsFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoMetrics.java
  reactor-core/src/main/java/reactor/core/publisher/MonoMetricsFuseable.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMetricsFuseableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMetricsTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPeekFuseableTest.java
Labels: enhancement

#1216 Fix #1189 Add cache(Duration, Scheduler) alias
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCacheTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheTimeTest.java
Labels: enhancement

#1222 Corrects Kotlin sentence semantics
  src/docs/asciidoc/kotlin.adoc
Labels: documentation

#1224 see #1043 Fix marble diagrams
  README.md
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  src/docs/marble/_marble-flux-mono-src.graffle
  src/docs/marble/concatwithvalues.png
  src/docs/marble/ignorethens.png
  src/docs/marble/mergeordered.png
  src/docs/marble/onerrorresume.png
  src/docs/marble/onerrorresumewith.png
  src/docs/marble/thenempty.png
  src/docs/marble/thenmany.png
  src/docs/marble/thenreturn1.png
  src/docs/marble/whendelayerror.png
  src/docs/marble/whent.png
  src/docs/marble/windowuntil.png
  src/docs/marble/zipdelayerror1.png
  src/docs/marble/zipt1.png
  src/docs/marble/ziptdelayerror1.png
Labels: documentation
