Repository reactor/reactor-core, pull requests merged in 2018-10, with the labels that each got.

#1359 Fix minor grammar mistake
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: documentation

#1395 fix #1393 null can be passed to reduce lambda if cancelled, causing NPE
  reactor-core/src/main/java/reactor/core/publisher/MonoReduceSeed.java
  reactor-core/src/test/java/reactor/core/publisher/MonoReduceSeedTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoReduceTest.java
Labels: bug

#1406 Violation.DEFER_CANCELLATION
  docs/asciidoc/testing.adoc
  reactor-test/src/main/java/reactor/test/publisher/DefaultTestPublisher.java
  reactor-test/src/main/java/reactor/test/publisher/TestPublisher.java
  reactor-test/src/test/java/reactor/test/publisher/DefaultTestPublisherTests.java
Labels: enhancement

#1402 Fix typo in Flux#single documentation
  README.md
  reactor-core/src/main/java/reactor/core/Disposable.java
  reactor-core/src/main/java/reactor/core/publisher/EventLoopProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/LambdaMonoSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/main/java/reactor/core/publisher/RingBuffer.java
  reactor-core/src/test/java/reactor/core/ListCompositeDisposableTest.java
  reactor-core/src/test/java/reactor/core/publisher/EmitterProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferBoundaryTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCreateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctUntilChangedTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDoFinallyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFilterWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowBoundaryTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/TopicProcessorTest.java
  reactor-core/src/test/java/reactor/core/scheduler/InstantPeriodicWorkerTaskTest.java
  reactor-core/src/test/java/reactor/core/scheduler/RejectedExecutionTest.java
  reactor-core/src/test/java/reactor/core/scheduler/TimedSchedulerTest.java
Labels: chores/build, documentation
