Repository reactor/reactor-core, pull requests merged in 2018-06, with the labels that each got.

#1231 fix #1226 Correct NoSuchElementException on callable empty last()
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/test/java/reactor/core/publisher/MonoTakeLastOneTest.java
Labels: bug, need-backport-3.1

#1212 fix #1205 Have lift alternative that exposes the raw Publisher
  reactor-core/src/main/java/reactor/core/publisher/ConnectableLift.java
  reactor-core/src/main/java/reactor/core/publisher/ConnectableLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxLift.java
  reactor-core/src/main/java/reactor/core/publisher/FluxLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/GroupedLift.java
  reactor-core/src/main/java/reactor/core/publisher/GroupedLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoLift.java
  reactor-core/src/main/java/reactor/core/publisher/MonoLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelLift.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelLiftFuseable.java
  reactor-core/src/test/java/reactor/core/publisher/LiftFunctionTest.java
  reactor-core/src/test/java/reactor/core/publisher/OperatorsTest.java
Labels: PR-depends-on-PR, enhancement

#1235 Fix issue with missed concurrent requesting support for FluxTake
  reactor-core/src/main/java/reactor/core/publisher/FluxTake.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTakeTest.java
Labels: bug, consider backport

#1234 improve #1220 FluxUsingWhen termination/cancel detection, scan + tests
  reactor-core/src/main/java/reactor/core/publisher/FluxUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoUsingWhen.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoUsingWhenTest.java
Labels: enhancement

#1244 TestPublisher.createNoncompliant().mono() would become compliant
  reactor-test/src/main/java/reactor/test/publisher/DefaultTestPublisher.java
  reactor-test/src/test/java/reactor/test/publisher/DefaultTestPublisherTests.java
Labels: reactor-test

#1248 fix #1247 Multiple bufferTimeout and bufferWhen issues
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferWhen.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferWhenTest.java
Labels: PR-fast-track, blocks-PR

#1249 fix #1240 Improve onCancel vs onDispose differentiation in javadoc
  reactor-core/src/main/java/reactor/core/publisher/FluxSink.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSink.java
Labels: documentation

#1263 fix #1259 Context propagation to commit/rollback publisher in usingWhen
  reactor-core/src/main/java/reactor/core/publisher/FluxUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoUsingWhen.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoUsingWhenTest.java
Labels: enhancement

#1271 [build] Have Travis test all for PR builds on maintenance branches
  travis-build.sh
Labels: PR-fast-track
