Repository reactor/reactor-core, pull requests merged in 2018-03, with the labels that each got.

#1108 fix #1107 Avoid interrupting WorkerTask Future if cancelled race
  reactor-core/src/main/java/reactor/core/scheduler/WorkerTask.java
  reactor-core/src/test/java/reactor/core/scheduler/WorkerTaskTest.java
Labels: enhancement

#1104 fix #648 Make StepVerifier.withVirtualTime mutally exclusive
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: enhancement, reactor-test

#1110 fix #1100 Add a Mono#error(Supplier) variant
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxErrorSupplied.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoErrorSupplied.java
  reactor-core/src/test/java/reactor/core/publisher/FluxErrorSuppliedTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoErrorSuppliedTest.java
  src/docs/asciidoc/apdx-operatorChoice.adoc
Labels: enhancement

#1112 fix #1101 concatMapDelayError default behavior is END
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
Labels: API change

#1109 for #1102 Detect some blocking APIs inside parallel and single Scheduler
  reactor-core/src/main/java/reactor/core/publisher/BlockingOptionalMonoSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/BlockingSingleSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/NonBlocking.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ReactorThreadFactory.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
  reactor-core/src/test/java/reactor/core/publisher/BlockingTests.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSubscribeOnTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  src/docs/asciidoc/apdx-operatorChoice.adoc
  src/docs/asciidoc/coreFeatures.adoc
Labels: enhancement

#1087 fix #1077 Allow naming of a whole StepVerifier scenario through options
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/main/java/reactor/test/ErrorFormatter.java
  reactor-test/src/main/java/reactor/test/StepVerifierOptions.java
  reactor-test/src/test/java/reactor/test/DefaultContextExpectationsTest.java
  reactor-test/src/test/java/reactor/test/ErrorFormatterTest.java
  reactor-test/src/test/java/reactor/test/StepVerifierAssertionsTests.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
  src/docs/asciidoc/testing.adoc
Labels: PR-review-needed, enhancement

#1126 fix #1118 onErrorDropped also logs error, MonoCompletionStage drops
  reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCompletionStageTest.java
Labels: bug, enhancement, need-backport-3.1

#1134 Fix for #1124 issue added verifyThenAssertThat(Duration)
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/main/java/reactor/test/StepVerifier.java
  reactor-test/src/test/java/reactor/test/StepVerifierAssertionsTests.java
  reactor-test/src/test/java/reactor/test/StepVerifierTimeoutTests.java
Labels: enhancement, reactor-test

#1138 fix #1135 Document (im)mutability of Tuple2 toList() vs iterator()
  reactor-core/src/main/java/reactor/util/function/Tuple2.java
Labels: documentation
