Repository reactor/reactor-core, pull requests merged in 2018-11, with the labels that each got.

#1412 disposed worker should reject scheduling a task with zero period
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
Labels: enhancement

#1419 Flux -> Mono in Javadoc
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: documentation

#1409 fix #1408 Add ability to multi-decorate backing ExecutorServices
  reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Scheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
Labels: PR-fast-track
