Repository reactor/reactor-core, pull requests merged in 2018-02, with the labels that each got.

#1065 Fix JavaDocs typo in expand function documentation
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: documentation

#1068 Just a typo in FluxJust.java
  reactor-core/src/main/java/reactor/core/publisher/FluxJust.java
Labels: PR-fast-track

#1049 fix #1048 Detect Context trigger object in repeatWhen/retryWhen
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRepeatWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRepeatWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
Labels: enhancement

#1075 fix #1074 Shutdown request task executor in event loop's forceShutdown
  reactor-core/src/main/java/reactor/core/publisher/EventLoopProcessor.java
Labels: bug

#1073 fix #1071 - make sure Mono.zip short circuit onComplete
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoZip.java
  reactor-core/src/test/java/reactor/core/publisher/MonoZipTest.java
Labels: bug

#1082 fix #1080 Only terminate ExecutorScheduler if underlying is shut down
  reactor-core/src/main/java/reactor/core/scheduler/ExecutorScheduler.java
  reactor-core/src/test/java/reactor/core/scheduler/ExecutorSchedulerTest.java
Labels: bug, need-backport-3.1

#1085 fix #1078 - do not throw dropped errors and callback hook
  reactor-core/src/main/java/reactor/core/publisher/FluxCreate.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCreate.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCreateTest.java
Labels: bug, need-backport-3.1

#1086 Fix typo "testcompile" to "testCompile"
  src/docs/asciidoc/testing.adoc
Labels: need-backport-3.1

#1092 fix #1090 Warn on doOnSubscribe usage
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
Labels: need-backport-3.1

#1094 Group by fixes
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
Labels: need-backport-3.1

#1096 fix #1088 FluxRefCount DisconnectException on cancellation race
  reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountTest.java
Labels: bug, need-backport-3.1
