Repository reactor/reactor-core, pull requests merged in 2019-12, with the labels that each got.

#1980 fix #1924 Discard elements of Collection in collect(), cover more cases
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCollect.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCollectList.java
  reactor-core/src/main/java/reactor/core/publisher/MonoStreamCollector.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCollectTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoStreamCollectorTest.java
Labels: warn/behavior-change

#1983 Do not instrument CGLIB proxies
  reactor-tools/build.gradle
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugAgent.java
  reactor-tools/src/test/java/reactor/tools/agent/ReactorDebugAgentTest.java
Labels: area/devexp, type/enhancement

#1988 Explicit `currentContext()`
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/BlockingIterable.java
  reactor-core/src/main/java/reactor/core/publisher/BlockingOptionalMonoSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/BlockingSingleSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/MonoToCompletableFuture.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/main/java/reactor/core/publisher/StrictSubscriber.java
  reactor-core/src/test/java/reactor/core/CoreSubscriberArchTest.java
Labels: type/bug, type/chores
