Repository reactor/reactor-core, pull requests merged in 2019-05, with the labels that each got.

#1672 Improve the callsite trace formatting
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/Traces.java
  reactor-core/src/test/java/reactor/HooksTraceTest.java
  reactor-core/src/test/java/reactor/core/ScannableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
  reactor-core/src/test/java/reactor/core/publisher/HooksTest.java
  reactor-core/src/test/java/reactor/core/publisher/TracesTest.java
  reactor-core/src/test/java/reactor/guide/GuideDebuggingExtraTests.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
Labels: enhancement

#1690 Use BlockHound 1.0.0.M3 instead of a SNAPSHOT
  reactor-core/build.gradle
Labels: chores/build

#1677 Do not mark `onEachOperatorHook` field as volatile.
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
Labels: Behavior change :warning:, discussion/design

#1691 Remove the Kotlin support (moved to reactor-kotlin)
  build.gradle
  docs/asciidoc/index.asciidoc
  docs/asciidoc/kotlin.adoc
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/MonoBridges.java
  reactor-core/src/main/kotlin/reactor/core/publisher/FluxExtensions.kt
  reactor-core/src/main/kotlin/reactor/core/publisher/MonoExtensions.kt
  reactor-core/src/main/kotlin/reactor/core/publisher/MonoFunctions.kt
  reactor-core/src/main/kotlin/reactor/util/function/TupleExtensions.kt
  reactor-core/src/test/kotlin/reactor/core/publisher/FluxExtensionsTests.kt
  reactor-core/src/test/kotlin/reactor/core/publisher/MonoExtensionsTests.kt
  reactor-core/src/test/kotlin/reactor/core/publisher/MonoFunctionsTests.kt
  reactor-core/src/test/kotlin/reactor/util/function/TupleExtensionsTests.kt
  reactor-test/build.gradle
  reactor-test/src/main/kotlin/reactor/test/StepVerifierExtensions.kt
  reactor-test/src/test/kotlin/reactor/test/StepVerifierExtensionsTests.kt
Labels: API change :warning:, kotlin

#1695 fix #1051 Move EventLoopProcessor to reactor-extra
  docs/asciidoc/processors.adoc
  reactor-core/src/main/java/reactor/core/Scannable.java
  reactor-core/src/main/java/reactor/core/publisher/EventLoopProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/RingBuffer.java
  reactor-core/src/main/java/reactor/core/publisher/TopicProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/WorkQueueProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/package-info.java
  reactor-core/src/test/java/reactor/core/publisher/EventLoopProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/TopicProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/WorkQueueProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/BurstyWorkQueueProcessorTests.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/CombinationTests.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/ConsistentProcessorTests.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FizzBuzzTests.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
  reactor-core/src/test/java/reactor/core/publisher/tck/FluxWithProcessorVerification.java
  reactor-core/src/test/java/reactor/core/publisher/tck/TopicProcessorVerification.java
  reactor-core/src/test/java/reactor/core/publisher/tck/WorkQueueProcessorVerification.java
  reactor-core/src/test/resources/logback.xml
Labels: API change :warning:

#1696 fix #1052 Move WaitStrategy to reactor-extra
  reactor-core/src/main/java/reactor/core/publisher/MonoProcessor.java
  reactor-core/src/main/java/reactor/util/concurrent/WaitStrategy.java
  reactor-core/src/main/java/reactor/util/concurrent/package-info.java
Labels: API change :warning:

#1698 [docs] Fix bad blocks in refguide causing formatting errors
  docs/asciidoc/advancedFeatures.adoc
  docs/asciidoc/apdx-reactorExtra.adoc
  docs/asciidoc/coreFeatures.adoc
  docs/asciidoc/debugging.adoc
  docs/asciidoc/faq.adoc
  docs/asciidoc/gettingStarted.adoc
  docs/asciidoc/processors.adoc
  docs/asciidoc/reactiveProgramming.adoc
  docs/asciidoc/snippetRetryWhenRetry.adoc
  docs/asciidoc/subscribe-backpressure.adoc
  docs/asciidoc/subscribe-details.adoc
  docs/asciidoc/testing.adoc
Labels: PR-fast-track, documentation

#1702 Fix light assembly tracing
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
Labels: bug

#1718 [build] Dokka bump to 0.9.18 for no HTTP, fix configuration
  build.gradle
Labels: PR-fast-track

#1721 fix #1719 Fix a memory barrier regression introduced in MonoSubscriber
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSubscriberTest.java
Labels: bug

#1717 fix #1707 Allow to chose a Scheduler for retryBackoff
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoRetryWhenTest.java
Labels: enhancement, need-forward-merge
