Repository reactor/reactor-core, pull requests merged in 2019-02, with the labels that each got.

#1505 Fix GAV for org.reactivestreams:reactive-streams:1.0.2
  docs/asciidoc/gettingStarted.adoc
Labels: documentation

#1502 Bugfix for cancellation before terminal signal in SwitchOnFirst
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchOnFirstTest.java
Labels: bug

#1534 Fix a race in FluxBufferTimeout on flush.
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferTimeout.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java
Labels: bug, need-forward-merge
