Repository reactor/reactor-core, pull requests merged in 2019-04, with the labels that each got.

#1648 fix #1647 Null out lastKey to avoid retaining in distinctUntilChanged
  reactor-core/src/main/java/reactor/core/publisher/FluxDistinctUntilChanged.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctUntilChangedTest.java
Labels: PR-fast-track

#1646 Fix light checkpoints in the backtrace
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
Labels: enhancement

#1657 fix #1656 ParallelFlux#doOnEach should receive the context
  reactor-core/src/main/java/reactor/core/publisher/ParallelDoOnEach.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/test/java/reactor/core/publisher/ParallelFluxTest.java
Labels: bug
