Repository reactor/reactor-core, pull requests merged in 2019-08, with the labels that each got.

#1831 fix #1684 Flux#flatMap with scalar source now supports onErrorContinue
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatMap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFlatMap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxMergeSequential.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchMap.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFlatMap.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFlatMapMany.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java
Labels: area/onErrorContinue

#1845 Trivial doc update
  reactor-core/src/main/java/reactor/core/publisher/BlockingOptionalMonoSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/ConnectableFlux.java
  reactor-core/src/main/java/reactor/core/publisher/EventLoopProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDetach.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoFirst.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoFirstFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxEmpty.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFromMonoOperator.java
  reactor-core/src/main/java/reactor/core/publisher/FluxNever.java
  reactor-core/src/main/java/reactor/core/publisher/FluxOperator.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoEmpty.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
Labels: type/documentation

#1856 fix #1706 again: bufferUntilChanged now uses defer to avoid shared state
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java
Labels: type/bug

#1862 Make it possible to run two JMH tasks - baseline and current
  benchmarks/README.md
  benchmarks/build.gradle
  gradle.properties
Labels: type/chores

#1868 fix #1854 Deprecate Mono#do[On|After]SuccessOrError for removal in 3.4
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: warn/deprecation

#1852 fix #1687 Change usingWhen API to use BiFunction for error handler
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/usingWhenFailureForFlux.svg
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/usingWhenFailureForMono.svg
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoUsingWhenTest.java
Labels: warn/deprecation
