Repository reactor/reactor-core, pull requests merged in 2019-06, with the labels that each got.

#1301 fix #1185 Avoid unbounded Flux.replay request with bounded subscribers
  reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java
  reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java
Labels: Behavior change :warning:

#1731 Move reactor-tools into the core repository
  reactor-tools/build.gradle
  reactor-tools/src/jarFileTest/java/reactor/tools/AbstractJarFileTest.java
  reactor-tools/src/jarFileTest/java/reactor/tools/JarFileShadingTest.java
  reactor-tools/src/main/java/reactor/tools/agent/CallSiteInfoAddingMethodVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ConstantSupplier.java
  reactor-tools/src/main/java/reactor/tools/agent/HooksClassVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugAgent.java
  reactor-tools/src/main/java/reactor/tools/agent/ReturnHandlingMethodVisitor.java
  reactor-tools/src/test/java/reactor/tools/agent/ReactorDebugAgentTest.java
  settings.gradle
Labels: chores/build, enhancement

#1737 Added code fences in reference guide
  docs/asciidoc/advancedFeatures.adoc
  docs/asciidoc/apdx-operatorChoice.adoc
  docs/asciidoc/apdx-reactorExtra.adoc
  docs/asciidoc/apdx-writingOperator.adoc
  docs/asciidoc/coreFeatures.adoc
  docs/asciidoc/debugging.adoc
  docs/asciidoc/faq.adoc
  docs/asciidoc/gettingStarted.adoc
  docs/asciidoc/kotlin.adoc
  docs/asciidoc/processors.adoc
  docs/asciidoc/producing.adoc
  docs/asciidoc/reactiveProgramming.adoc
  docs/asciidoc/snippetRetryWhenRetry.adoc
  docs/asciidoc/subscribe-backpressure.adoc
  docs/asciidoc/subscribe-details.adoc
  docs/asciidoc/testing.adoc
Labels: documentation

#1740 Remove "checkpoint" prefix from return-only callsites
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/Traces.java
  reactor-core/src/test/java/reactor/core/publisher/TracesTest.java
  reactor-tools/build.gradle
  reactor-tools/src/main/java/reactor/tools/agent/CallSiteInfoAddingMethodVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ConstantSupplier.java
  reactor-tools/src/main/java/reactor/tools/agent/HooksClassVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugAgent.java
  reactor-tools/src/main/java/reactor/tools/agent/ReturnHandlingMethodVisitor.java
  reactor-tools/src/test/java/reactor/tools/agent/ReactorDebugAgentTest.java
Labels: enhancement

#1748 fix #1742 Polish processor deprecations
  docs/asciidoc/processors.adoc
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/TopicProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/WorkQueueProcessor.java
  reactor-core/src/main/java/reactor/util/concurrent/WaitStrategy.java
Labels: PR-fast-track

#1757 Display source code as java
  docs/asciidoc/coreFeatures.adoc
Labels: documentation

#1746 Add "VirtualTimeScheduler#getScheduledTaskCount()"
  reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java
  reactor-test/src/test/java/reactor/test/scheduler/VirtualTimeSchedulerTests.java
Labels: reactor-test

#1768 fix #1767 Add ParallelFlux#then to compose on parallel termination
  reactor-core/src/main/java/reactor/core/publisher/MonoIgnoreThen.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelMergeReduce.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelThen.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
  reactor-core/src/test/java/reactor/core/publisher/ParallelThenTest.java
Labels: PR-fast-track

#1770 1769 revert context caching
  reactor-core/src/main/java/reactor/core/publisher/FluxBuffer.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/FluxCombineLatest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatMap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFlatMap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java
Labels: PR-fast-track
