Repository reactor/reactor-core, pull requests merged in 2019-11, with the labels that each got.

#1961 fix #1959 GroupedFlux fused with parallel() not replenishing properly
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
Labels: need-forward-merge, type/bug

#1902 #1888 detect Context loss
  reactor-core/src/main/java/reactor/core/publisher/ContextTrackingFunctionWrapper.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/ContextLossDetectionTest.java
Labels: area/devexp, for/team-attention, type/enhancement

#1947 Polish
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/chores

#1969 fix #1968 Make FluxPublish propagate 1st subscriber context
  reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java
Labels: type/bug

#1954 fix #1953 Add Exceptions.isTraceback
  docs/asciidoc/debugging.adoc
  reactor-core/src/main/java/reactor/core/Exceptions.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/test/java/reactor/core/ExceptionsTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
Labels: for/merge-with-rebase

#1971 fix #1970 Avoid creating Map.Entry in Context.putAll
  reactor-core/src/main/java/reactor/util/context/Context.java
  reactor-core/src/main/java/reactor/util/context/Context0.java
  reactor-core/src/main/java/reactor/util/context/Context1.java
  reactor-core/src/main/java/reactor/util/context/Context2.java
  reactor-core/src/main/java/reactor/util/context/Context3.java
  reactor-core/src/main/java/reactor/util/context/Context4.java
  reactor-core/src/main/java/reactor/util/context/Context5.java
  reactor-core/src/main/java/reactor/util/context/ContextN.java
  reactor-core/src/main/java/reactor/util/context/CoreContext.java
  reactor-core/src/test/java/reactor/util/context/Context0Test.java
  reactor-core/src/test/java/reactor/util/context/Context1Test.java
  reactor-core/src/test/java/reactor/util/context/Context2Test.java
  reactor-core/src/test/java/reactor/util/context/Context3Test.java
  reactor-core/src/test/java/reactor/util/context/Context4Test.java
  reactor-core/src/test/java/reactor/util/context/Context5Test.java
  reactor-core/src/test/java/reactor/util/context/ContextNTest.java
  reactor-core/src/test/java/reactor/util/context/ContextTest.java
  reactor-core/src/test/java/reactor/util/context/CoreContextTest.java
Labels: for/team-attention
