Repository reactor/reactor-core, pull requests merged in 2019-07, with the labels that each got.

#1775 Adjust benchmarks' build config after Gradle's update
  benchmarks/build.gradle
Labels: PR-fast-track, chores/build

#1776 Use "check" task as an aggregator, not "test"
  reactor-core/build.gradle
Labels: chores/build

#1785 fix #1738 FluxRefCount inner doesn't guard against multiple cancels
  reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountTest.java
Labels: bug

#1796 Add missing spaces in Javadoc
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: documentation

#1795 Record executor service metrics to Micrometer
  reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersMetricsTest.java
Labels: enhancement

#1781 Move original stacktrace after the backtrace
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
  reactor-core/src/test/java/reactor/guide/GuideDebuggingExtraTests.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
Labels: enhancement

#1809 Metrics guide
  docs/asciidoc/index.asciidoc
  docs/asciidoc/metrics.adoc
  reactor-core/src/main/java/reactor/core/publisher/FluxMetrics.java
Labels: documentation

#1817 Update a link to Micrometer's docs for the executor metrics
  docs/asciidoc/metrics.adoc
Labels: documentation

#1819 fix #1816 Add a Context-aware {Mono,Flux}.defer
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDeferWithContext.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDeferWithContext.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDeferTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDeferTest.java
Labels: enhancement, need-decision

#1822 fix #1451 Dematerialize needs extra request(1) for terminal signals...
  reactor-core/src/main/java/reactor/core/publisher/FluxDematerialize.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDematerialize.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDematerializeTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDematerializeTest.java
  reactor-core/src/test/java/reactor/core/publisher/tck/AbstractFluxVerification.java
Labels: Behavior change :warning:

#1824 Polish codebase to fix compiler warnings/suppress some in tests
  reactor-core/src/main/java/reactor/core/publisher/EventLoopProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheTime.java
  reactor-core/src/main/java/reactor/core/publisher/MonoPublishMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/RingBuffer.java
  reactor-core/src/main/java/reactor/core/publisher/TopicProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/WorkQueueProcessor.java
  reactor-core/src/main/kotlin/reactor/core/publisher/FluxExtensions.kt
  reactor-core/src/test/java/reactor/core/publisher/FluxDeferComposeTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDoFirstTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDoOnEachTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchOnFirstTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCollectTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDeferComposeTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDoFirstTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDoOnEachTest.java
  reactor-core/src/test/java/reactor/core/publisher/OperatorsTest.java
  reactor-core/src/test/java/reactor/core/publisher/ParallelFluxTest.java
  reactor-core/src/test/kotlin/reactor/core/publisher/FluxExtensionsTests.kt
  reactor-core/src/test/kotlin/reactor/core/publisher/MonoExtensionsTests.kt
  reactor-core/src/test/kotlin/reactor/core/publisher/MonoFunctionsTests.kt
  reactor-core/src/test/kotlin/reactor/util/function/TupleExtensionsTests.kt
  reactor-test/src/main/java/reactor/test/ValueFormatters.java
  reactor-test/src/test/java/reactor/test/StepVerifierOptionsTest.java
  reactor-test/src/test/java/reactor/test/ValueFormattersTest.java
  reactor-test/src/test/kotlin/reactor/test/StepVerifierExtensionsTests.kt
Labels: chores/build

#1821 [Trivial]Simple documentation update
  docs/asciidoc/producing.adoc
Labels: documentation

#1820 Update ParallelFlux.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
Labels: documentation

#1826 Avoid `instanceof` check in `onLastAssembly` if the hook is null
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
Labels: enhancement
