Repository reactor/reactor-core, pull requests merged in 2020-04, with the labels that each got.

#2095 Propagate rejection error from `MonoDelayElement#onNext` downstream
  reactor-core/src/main/java/reactor/core/publisher/MonoDelayElement.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDelayElementTest.java
Labels: type/bug

#2072 Unify handling of errors thrown by `subscribeOrReturn`
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferBoundary.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java
  reactor-core/src/main/java/reactor/core/publisher/FluxContextStart.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDistinct.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDistinctFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoFirst.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoFirstFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFromMonoOperator.java
  reactor-core/src/main/java/reactor/core/publisher/FluxMergeOrdered.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublishMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublishOn.java
  reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSubscribeOn.java
  reactor-core/src/main/java/reactor/core/publisher/FluxZip.java
  reactor-core/src/main/java/reactor/core/publisher/FluxZipIterable.java
  reactor-core/src/main/java/reactor/core/publisher/InternalConnectableFluxOperator.java
  reactor-core/src/main/java/reactor/core/publisher/InternalFluxOperator.java
  reactor-core/src/main/java/reactor/core/publisher/InternalMonoOperator.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCollect.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDelayUntil.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDoFirst.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDoFirstFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFlattenIterable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFromFluxOperator.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFromPublisher.java
  reactor-core/src/main/java/reactor/core/publisher/MonoIgnorePublisher.java
  reactor-core/src/main/java/reactor/core/publisher/MonoPublishMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/MonoReduceSeed.java
  reactor-core/src/main/java/reactor/core/publisher/MonoStreamCollector.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSubscriberContext.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/main/java/reactor/core/publisher/OptimizableOperator.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeOrderedTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
  reactor-core/src/test/java/reactor/test/publisher/FluxFuseableExceptionOnPoll.java
Labels: type/enhancement, wide-change

#2097 Create CODEOWNERS
  .github/CODEOWNERS
Labels: type/chores

#2102 Provide onDiscard support in UnicastProcessor
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
Labels: area/doOnDiscard, type/enhancement

#2104 Support running reactor-tools as a "normal" Java Agent
  reactor-tools/build.gradle
  reactor-tools/src/javaAgentTest/java/reactor/tools/agent/ReactorDebugJavaAgentTest.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugAgent.java
Labels: area/devexp, type/enhancement

#2105 Support build-time debug instrumentation
  docs/asciidoc/debugging.adoc
  reactor-tools/build.gradle
  reactor-tools/src/buildPluginTest/java/reactor/tools/agent/ReactorDebugBuildPluginTest.java
  reactor-tools/src/jarFileTest/java/reactor/tools/JarFileShadingTest.java
  reactor-tools/src/main/java/reactor/tools/agent/CallSiteInfoAddingMethodVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugAgent.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugByteBuddyPlugin.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugClassVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ReturnHandlingMethodVisitor.java
Labels: area/devexp, type/enhancement

#2099 [test] Split `errorOnSubscribe` scenarios into separate tests
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
Labels: type/chores

#2115 fix #2112 Don't reuse same exception in `errorOnSubscribe` steps
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
Labels: type/chores

#2111 Fix #2107 by throwing (and checking) a specialized error
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDoFirstTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDoFirstTest.java
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: area/reactor-test, type/bug

#2126 fix #2124 Backport and improve discard handling in UnicastProcessor
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/core/publisher/UnicastProcessorTest.java
Labels: area/doOnDiscard

#2134 Fix onDiscard leaks in fused operators with queue
  reactor-core/src/main/java/reactor/core/publisher/FluxOnBackpressureBuffer.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublishOn.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
Labels: area/doOnDiscard, type/enhancement

#2135 [doc] Polish doc of Iterable operators, clarify iterator() calls
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: area/doOnDiscard, type/documentation

#2110 Remove wrong curly braces in `generate` code example
  docs/asciidoc/producing.adoc
Labels: type/documentation
