Repository reactor/reactor-core, pull requests merged in 2020-10, with the labels that each got.

#2412 Fix concurrent terminal signal detection in `SerializedManySink`
  reactor-core/src/jcstress/java/reactor/core/publisher/SerializedManySinkStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
Labels: type/bug

#2405 See #2377 Add `emitXxx(EmitFailureHandler)` Sinks API
  reactor-core/src/jcstress/java/reactor/core/publisher/SerializedManySinkStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/EmitterProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/InternalEmptySink.java
  reactor-core/src/main/java/reactor/core/publisher/InternalManySink.java
  reactor-core/src/main/java/reactor/core/publisher/InternalOneSink.java
  reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/ReplayProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/SinkEmptyMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/SinkManyBestEffort.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastManySinkNoBackpressure.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  reactor-core/src/test/java/reactor/core/publisher/InternalManySinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/InternalOneSinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/SerializedManySinkTest.java
Labels: type/enhancement

#2421 [test] Polish tests that use nano durations to avoid flakkyness
  reactor-core/src/test/java/reactor/core/publisher/BlockingTests.java
  reactor-core/src/test/java/reactor/core/publisher/FluxIntervalTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java
Labels: type/chores

#2425 [test] Fix flakky boundedElasticScheduler test
  reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java
Labels: type/chores

#2418 Rework Sinks specs to put unsafe() at root level
  docs/asciidoc/processors.adoc
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupJoin.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindow.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowBoundary.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowWhen.java
  reactor-core/src/main/java/reactor/core/publisher/SinkEmptySerialized.java
  reactor-core/src/main/java/reactor/core/publisher/SinkManySerialized.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/publisher/AbstractFluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferBoundaryTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCombineLatestTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctUntilChangedTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFilterTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupJoinTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxJoinTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeSequentialTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureBufferStrategyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureDropTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureLatestTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPeekFuseableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPeekTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRepeatWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSampleFirstTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSampleTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSampleTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowBoundaryTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowPredicateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkManySerializedTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinksTest.java
  reactor-core/src/test/java/reactor/core/publisher/StrictSubscriberTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxWindowConsistencyTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: type/enhancement, warn/api-change

#2427 fix #2426 Rename Emission to EmitResult
  docs/asciidoc/processors.adoc
  reactor-core/src/jcstress/java/reactor/core/publisher/SinkEmptySerializedStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/SinkManySerializedStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/SinkOneSerializedStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/EmitterProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/InternalEmptySink.java
  reactor-core/src/main/java/reactor/core/publisher/InternalManySink.java
  reactor-core/src/main/java/reactor/core/publisher/InternalOneSink.java
  reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/ReplayProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/SinkEmptyMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/SinkEmptySerialized.java
  reactor-core/src/main/java/reactor/core/publisher/SinkManyBestEffort.java
  reactor-core/src/main/java/reactor/core/publisher/SinkManySerialized.java
  reactor-core/src/main/java/reactor/core/publisher/SinkOneSerialized.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastManySinkNoBackpressure.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  reactor-core/src/test/java/reactor/core/publisher/EmitterProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java
  reactor-core/src/test/java/reactor/core/publisher/InternalManySinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/InternalOneSinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkEmptyMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkManyBestEffortTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkManySerializedTest.java
  reactor-core/src/test/java/reactor/core/publisher/UnicastManySinkNoBackpressureTest.java
  reactor-core/src/test/java/reactor/core/publisher/UnicastProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxSpecTests.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
Labels: type/enhancement, warn/api-change

#2432 fix #2431 Deprecate [Flux|Mono]Processor contracts entirely
  docs/asciidoc/faq.adoc
  docs/asciidoc/processors.adoc
  reactor-core/src/main/java/reactor/core/publisher/DelegateProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/DelegateSinkFluxProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/DelegateSinkOneMonoProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/CurrentContextArchTest.java
  reactor-core/src/test/java/reactor/core/publisher/DelegateProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeSequentialTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSourceTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoFilterTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoFirstWithSignalTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoOnErrorResumeTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoPublishMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoUsingTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoZipTest.java
  reactor-core/src/test/java/reactor/core/publisher/NextProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
  reactor-core/src/test/java/reactor/core/publisher/tck/EmitterProcessorVerification.java
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
Labels: warn/api-change

#2441 fix #2436 Polish some 3.2 JUnit5 tests and compiler options
  buildSrc/src/main/java/io/reactor/gradle/JavaConventions.java
  reactor-core/src/test/java/reactor/core/ExceptionsTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java
  reactor-core/src/test/java/reactor/core/scheduler/AbstractSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
Labels: type/chores

#2444 fix #2439 correctly use testNG platform for testNG task
  reactor-core/build.gradle
Labels: type/chores

#2455 fix #2454 Detail Sinks doc: EmitResult internal handling, safe vs unsafe
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
Labels: type/documentation

#2461 Japicmp: baseline at 3.4.0, remove exclusions and custom class
  gradle.properties
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: type/chores

#2463 [doc] Improve doOnDiscard/onErrorContinue javadoc a bit
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation

#2458 [doc] Improve firstWithValue doc on error/empty consequences (see #2459)
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFirstWithValueTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoFirstWithValueTest.java
Labels: type/documentation

#2457 [doc] Polish typos and SampleSubscriber snippet in ref guide
  docs/asciidoc/advancedFeatures.adoc
  docs/asciidoc/subscribe-details.adoc
  reactor-core/src/main/java/reactor/core/publisher/MonoCreate.java
Labels: type/documentation
