Repository reactor/reactor-core, pull requests merged in 2020-11, with the labels that each got.

#2469 [doc] Polish deprecation notes of processor factories javadocs
  reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/EmitterProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/ReplayProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
Labels: type/documentation

#2474 fix #2470 Make refguide BOM snippets use version from gradle.properties
  docs/asciidoc/gettingStarted.adoc
  gradle.properties
  gradle/asciidoc.gradle
Labels: type/chores, type/documentation

#2475 fix #2195 Add timed() operator
  docs/asciidoc/apdx-operatorChoice.adoc
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTimed.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTimed.java
  reactor-core/src/main/java/reactor/core/publisher/Timed.java
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/timedForFlux.svg
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/timedForMono.svg
  reactor-core/src/test/java/reactor/core/publisher/FluxTimedTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoTimedTest.java
Labels: type/enhancement

#2479 see #2173 Polish refguide operator choice: add firstWith[Value|Signal]
  docs/asciidoc/apdx-operatorChoice.adoc
Labels: type/documentation

#2490 fix #2483 Cleanup doOnSuccess marble diagram
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/doOnSuccess.svg
Labels: type/documentation

#2499 Make `RetryWhenMainSubscriber#onError`'s calls serial
  reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
Labels: type/bug
