Repository reactor/reactor-core, pull requests merged in 2020-05, with the labels that each got.

#2156 [build] Backport last relevant build changes from 3.3
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/io/reactor/gradle/CustomVersionPlugin.java
  buildSrc/src/main/java/io/reactor/gradle/DetectCiPlugin.java
  buildSrc/src/main/java/io/reactor/gradle/JavaConventions.java
  buildSrc/src/test/java/io/reactor/gradle/CustomVersionPluginTest.java
  buildSrc/src/test/java/io/reactor/gradle/DetectCiPluginTest.java
  gradle.properties
  gradle/asciidoc.gradle
  gradle/javadoc.gradle
  gradle/setup.gradle
  reactor-core/build.gradle
  reactor-test/build.gradle
  settings.gradle
Labels: type/chores

#2157 [polish] Consistently use tabs for gradle file indentation
  build.gradle
  gradle/asciidoc.gradle
  gradle/javadoc.gradle
  gradle/releaser.gradle
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: type/chores

#2158 fix #2151 Publish Gradle metadata, without optional dependencies
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/io/reactor/gradle/OptionalDependenciesPlugin.java
  buildSrc/src/test/java/io/reactor/gradle/OptionalDependenciesPluginTest.java
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: type/bug, type/chores

#2162 Fix RetrySpec doc: throwablePredicate is actually filter
  reactor-core/src/main/java/reactor/util/retry/RetryBackoffSpec.java
  reactor-core/src/main/java/reactor/util/retry/RetrySpec.java
Labels: type/documentation

#2159 [doc] Better describe Mono.first/or behavior
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation

#2166 Fix volatile read & conditionalSub classcast in switchOnFirst
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchOnFirstTest.java
Labels: type/bug

#2164 Ensure DeferredSubscription makes requests serially
  reactor-core/src/main/java/reactor/core/publisher/FluxUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/OperatorsTest.java
Labels: type/bug

#2161 Ensure SwitchOnFirst serializes requests per rule 2.7
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchOnFirstTest.java
Labels: type/bug

#2167 fix #2015 Document onCancel/onDipose limited to 1 use
  reactor-core/src/main/java/reactor/core/publisher/FluxSink.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSink.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCreateTest.java
Labels: type/documentation

#2172 [doc] Fix typo Retry.fromFunction instead of from
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation
