Repository reactor/reactor-core, pull requests merged in 2020-03, with the labels that each got.

#2061 fix #2056 Don't overwrite but merge Context in [repeat,retry]When
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRepeatWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRepeatWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
Labels: type/enhancement

#2073 Use JUnit Platform + Vintage engine
  build.gradle
  reactor-core/build.gradle
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-test/build.gradle
  reactor-tools/build.gradle
  reactor-tools/src/test/java/reactor/tools/agent/ReactorDebugAgentTest.java
Labels: type/chores

#2082 [test] Add a post-test listener that resets hooks consistently
  reactor-core/build.gradle
  reactor-core/src/test/java/reactor/HooksTraceTest.java
  reactor-core/src/test/java/reactor/ReactorTestExecutionListener.java
  reactor-core/src/test/java/reactor/core/ScannableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMetricsTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTakeTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
  reactor-core/src/test/java/reactor/core/publisher/HooksTest.java
  reactor-core/src/test/java/reactor/core/publisher/HooksTestStaticInit.java
  reactor-core/src/test/java/reactor/core/publisher/LambdaMonoSubscriberTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDelayElementTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoMetricsTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnNextFailureStrategyTest.java
  reactor-core/src/test/java/reactor/core/publisher/OperatorDisposablesTest.java
  reactor-core/src/test/java/reactor/core/publisher/OperatorsTest.java
  reactor-core/src/test/java/reactor/core/publisher/TailCallSubscribeTest.java
  reactor-core/src/test/java/reactor/core/scheduler/RejectedExecutionTest.java
  reactor-core/src/test/java/reactor/guide/GuideDebuggingExtraTests.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
  reactor-core/src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
Labels: type/chores

#2085 [test] Use JUnit Jupiter's `@TestFactory` in BaseOperatorTest
  reactor-core/src/test/java/reactor/test/publisher/BaseOperatorTest.java
  reactor-core/src/test/java/reactor/test/publisher/OperatorScenario.java
Labels: type/chores

#2091 Polish build californium
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: for/merge-with-rebase, type/chores

#2093 [test] Remove testStaticInit task, verify in main test task
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/test/java/reactor/core/publisher/HooksTest.java
  reactor-core/src/test/java/reactor/core/publisher/HooksTestStaticInit.java
Labels: type/chores

#2089 [build] Follow-up to #2088 bump to Gradle 6.3 : 3.3 specifics
  build.gradle
  reactor-core/build.gradle
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctUntilChangedTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  settings.gradle
Labels: type/chores
