Repository reactor/reactor-core, pull requests merged in 2020-12, with the labels that each got.

#2505 fix #2502 Generate OSGI Bundle-Version from Europium+ scheme
  build.gradle
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: type/chores

#2522 [doc] Use https for Reactive Streams link in javadoc header
  docs/api/overview.html
Labels: type/documentation

#2518 Say from which operator the asserted Context was taken
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/test/java/reactor/test/DefaultContextExpectationsTest.java
Labels: area/context, area/reactor-test

#2524 fix #2504 Better reflect time of execution of doOn* handlers in javadoc
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation

#2528 fix #2527 Also run CI on master/maintenance branches
  .github/workflows/ci.yml
  reactor-core/src/test/java/reactor/core/publisher/SerializedSubscriberTest.java
Labels: for/merge-with-rebase, type/chores

#2530 [test] Disable flaky test on 3.2.x only
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/MonoMetricsTest.java
Labels: for/fast-track, type/chores

#2450 Fix groupBy initial request off by one
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
Labels: type/bug, type/enhancement

#2535 fix #2534 Fix leak in MonoSingle and improve MonoSubscriber setValue
  reactor-core/src/main/java/reactor/core/publisher/FluxDefaultIfEmpty.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCollect.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCollectList.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDelayUntil.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFilterWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoReduce.java
  reactor-core/src/main/java/reactor/core/publisher/MonoReduceSeed.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingle.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTakeLastOne.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/test/MemoryUtils.java
Labels: area/doOnDiscard, type/bug
