Repository reactor/reactor-core, pull requests merged in 2020-09, with the labels that each got.

#2348 [build] Add Gradle wrapper validation
  .github/workflows/gradle-wrapper-validation.yml
Labels: type/chores

#2347 Add `onBackpressureError()` variant of the unicast Sink
  reactor-core/src/main/java/reactor/core/publisher/ContextHolder.java
  reactor-core/src/main/java/reactor/core/publisher/FluxProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastManySinkNoBackpressure.java
  reactor-core/src/test/java/reactor/core/publisher/SerializedManySinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/UnicastManySinkNoBackpressureTest.java
Labels: type/enhancement

#2351 [doc] Polish variable names in snippet
  docs/asciidoc/testing.adoc
Labels: type/chores, type/documentation

#2359 Fix spelling mistake in Tuple2
  reactor-core/src/main/java/reactor/util/function/Tuple2.java
Labels: type/chores, type/documentation

#2364 fix #2362 Prevent ConcurrentModificationEx on bufferPredicate discard
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferPredicate.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java
Labels: area/doOnDiscard

#2373 Polish javadoc of the multicast onBackpressureBuffer Sinks
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
Labels: type/documentation

#2365 Fail fast on non serialized access to Sink
  reactor-core/src/jcstress/java/reactor/core/publisher/SerializedManySinkStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRepeatWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/publisher/SerializedManySinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/UnicastProcessorTest.java
Labels: type/enhancement

#2378 fix #2374 Deprecate Sinks `emit{Next,Error,Complete}` methods
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
Labels: warn/deprecation

#2376 fix #2375 Remove `Sinks.many().multicast().onBackpressureError()`
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/publisher/AbstractFluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferBoundaryTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCombineLatestTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDistinctUntilChangedTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupJoinTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxJoinTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeSequentialTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureBufferStrategyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureDropTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureLatestTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRepeatWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSampleFirstTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSampleTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSampleTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowBoundaryTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowPredicateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/SerializedManySinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/StrictSubscriberTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxWindowConsistencyTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: warn/api-change

#2384 [doc typo] Fix List ref name in hybrid push/pull code
  docs/asciidoc/producing.adoc
Labels: type/documentation
