Repository reactor/reactor-core, pull requests merged in 2020-07, with the labels that each got.

#2202 Allow "0" prefetch value in `concatMap`
  reactor-core/build.gradle
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxConcatMapNoPrefetchStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatMapNoPrefetch.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/AbstractFluxConcatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatMapNoPrefetchTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatMapTest.java
Labels: type/enhancement

#2245 Handle `null` publisher in `MonoDelayUntil`
  reactor-core/src/main/java/reactor/core/publisher/MonoDelayUntil.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDelayUntilTest.java
Labels: type/bug

#2247 [build] Bump Kotlin to 1.3.72
  build.gradle
Labels: area/kotlin, type/chores

#2255 polish travis build for JDK download and remove complicated travis script
  .travis.yml
  build.gradle
  travis-build.sh
Labels: for/merge-with-rebase

#2263 fix #2262 Make the fact that optional are not in pom anymore explicit
  gradle/setup.gradle
Labels: type/chores

#2271 [polish] FluxUsingWhenTest awaitility + order of capturing subscription
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
Labels: type/chores

#2266 fix #2260 Avoid onSubscribe race in FluxTimeout
  reactor-core/src/main/java/reactor/core/publisher/FluxTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTimeout.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTimeoutTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoTimeoutTest.java
Labels: type/bug, warn/behavior-change

#1789 Decorate executors in start() rather than constructor (see #1778)
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ImmediateScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
  reactor-core/src/test/java/reactor/core/scheduler/AbstractSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/DelegateServiceSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ExecutorSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ExecutorSchedulerTrampolineTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ImmediateSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ParallelSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleWorkerAroundTimerSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleWorkerSchedulerTest.java
  reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java
Labels: type/enhancement, warn/behavior-change

#2248 [polish] In README Gradle snippet, put maven central repo first
  README.md
Labels: type/chores

#2286 [doc] Fix Mono#subscribeOn doc typo
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/chores

#2294 fix #2293 Reduce the impact of the ContextView introduction
  docs/asciidoc/advancedFeatures.adoc
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDeferContextual.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoOnEach.java
  reactor-core/src/main/java/reactor/core/publisher/ImmutableSignal.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheTime.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDeferContextual.java
  reactor-core/src/main/java/reactor/core/publisher/Signal.java
  reactor-core/src/main/java/reactor/util/context/Context.java
  reactor-core/src/test/java/reactor/core/publisher/ContextLossDetectionTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDeferContextualTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDeferTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDeferTest.java
  reactor-core/src/test/java/reactor/core/publisher/SignalTest.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
  reactor-core/src/test/java/reactor/util/context/ContextTest.java
Labels: for/merge-with-rebase
