Repository reactor/reactor-core, pull requests merged in 2020-06, with the labels that each got.

#2177 Have push(emitter) delegate to push(emitter, backpressure)
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/enhancement

#2209 fix #2208 Remove schedulers deprecated in 3.3
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/EventLoopProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/TopicProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/WorkQueueProcessor.java
Labels: warn/api-change

#2226 Rework linking between check, japicmp and downloadBaseline tasks
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: type/chores

#2190 [doc] Fix Scheduler Javadoc
  reactor-core/src/main/java/reactor/core/scheduler/Scheduler.java
Labels: type/documentation

#2230 [build] Remove compilation warnings related to jsr305
  benchmarks/build.gradle
  buildSrc/src/main/java/io/reactor/gradle/JavaConventions.java
  reactor-test/build.gradle
Labels: type/chores

#2232 [doc] Document Android 21 desugaring options
  README.md
  docs/asciidoc/gettingStarted.adoc
Labels: type/documentation
