Repository reactor/reactor-core, pull requests merged in 2021-01, with the labels that each got.

#2552 Mirror the SUPPORT health file in reference guide
  docs/asciidoc/gettingStarted.adoc
Labels: type/documentation

#2575 Fix some metrics tests to avoid implicit use of globalRegistry
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/FluxMetricsTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/MonoMetricsTest.java
Labels: type/chores

#2574 [build] Enforce NoHTTP with plugin and relevant exclusions
  benchmarks/README.md
  benchmarks/src/main/java/reactor/core/scrabble/ShakespearePlaysScrabble.java
  build.gradle
  codequality/nohttp/allowlist.lines
  docs/asciidoc/metrics.adoc
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/bufferTimeoutWithMaxSizeAndTimespan.svg
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/transformForFlux.svg
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/transformForMono.svg
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/util/retry/doc-files/marbles/retrySpecAttempts.svg
  reactor-core/src/main/java/reactor/util/retry/doc-files/marbles/retrySpecBackoff.svg
  reactor-core/src/main/java/reactor/util/retry/doc-files/marbles/retrySpecFixed.svg
  reactor-core/src/main/java/reactor/util/retry/doc-files/marbles/retrySpecInARow.svg
Labels: type/chores

#2573 Explain the Java 8/9 stubs
  reactor-core/build.gradle
Labels: area/devexp, type/chores
