Repository reactor/reactor-core, pull requests merged in 2021-09, with the labels that each got.

#2763 [doc] remove stray mid-sentence newlines
  docs/asciidoc/processors.adoc
Labels: type/documentation

#2756 Align Mono#share() behavior with Flux#share, split sink impl out
  reactor-core/src/main/java/reactor/core/publisher/InternalOneSink.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/SinkEmptyMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/SinkOneMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/publisher/NextProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkEmptyMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkOneMulticastTest.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: type/bug, type/enhancement

#2764 [reactor-test] Fix consumeWhile+expectRecorded* skipping signal
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
Labels: type/bug, area/reactor-test

#2741 Rework FluxReplay to avoid hanging, but reject 0 size
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java
  reactor-core/src/main/java/reactor/core/publisher/ReplayProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinksTest.java
Labels: type/bug, warn/behavior-change

#2767 Document that windows (and groupBy groups) are unicast
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/documentation

#2768 fixes improperly dropped error
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchOnFirstTest.java
Labels: type/bug

#2777 Tune test performanceOfContinuouslyCancellingGroup
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
Labels: type/chores

#2773 Polish parameterized tests for better display names
  buildSrc/src/main/java/io/reactor/gradle/JavaConventions.java
  reactor-core/src/test/java/reactor/core/publisher/ContextLossDetectionTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCreateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDoOnEachTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnBackpressureBufferStrategyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxStreamTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
  reactor-core/src/test/java/reactor/core/publisher/InternalManySinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/InternalOneSinkTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheTimeTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/test/ParameterizedTestWithName.java
  reactor-core/src/test/java/reactor/test/TestBestPracticesArchTest.java
  reactor-core/src/test/java/reactor/util/concurrent/QueuesTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/scheduler/SchedulersMetricsTest.java
Labels: type/chores

#2787 Document possible alternative to replay ManySink `limit(0)`
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
Labels: type/documentation

#2771 Mono.create sink now discards if emitting after cancel
  reactor-core/src/main/java/reactor/core/publisher/MonoCreate.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCreateTest.java
Labels: type/enhancement, area/doOnDiscard

#2775 Bump to Gradle 7.2, polish build and upgrade plugins/libraries
  benchmarks/build.gradle
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/io/reactor/gradle/JavaConventions.java
  gradle/setup.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  reactor-core/build.gradle
  reactor-core/src/test/java/reactor/core/CurrentContextArchTest.java
  reactor-core/src/test/java/reactor/core/QueueSubscriptionTest.java
  reactor-core/src/test/java/reactor/core/SwapDisposableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDetachTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDetachTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleSchedulerTest.java
  reactor-test/src/test/java/reactor/test/StepVerifierTests.java
  reactor-tools/build.gradle
  reactor-tools/src/jarFileTest/java/reactor/tools/JarFileShadingTest.java
  settings.gradle
Labels: type/chores

#2790 Polish Mono cache operators documentation
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation
