Repository reactor/reactor-core, pull requests merged in 2021-10, with the labels that each got.

#2799 Fix Mono.flatMapIterable javadoc: no prefetch parameter
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation

#2780 Prevent unnecessary duplicated lines in backtraces
  docs/asciidoc/debugging.adoc
  reactor-core/src/main/java/reactor/core/publisher/ConnectableFluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/FluxCallableOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCallableOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/MonoOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFluxOnAssembly.java
  reactor-core/src/test/java/reactor/HooksTraceTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
  reactor-core/src/test/java/reactor/core/publisher/HooksTest.java
  reactor-core/src/test/java/reactor/guide/GuideDebuggingExtraTests.java
  reactor-core/src/test/java/reactor/guide/GuideTests.java
  reactor-tools/src/test/java/reactor/tools/agent/ReactorDebugAgentTest.java
Labels: type/bug

#2791 ConcatArray: avoid next subscription if cancelled
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatArray.java
  reactor-core/src/test/java/reactor/core/publisher/FluxConcatArrayTest.java
Labels: type/bug

#2795 Fix Module was compiled with an incompatible version of Kotlin
  build.gradle
Labels: type/bug, type/chores

#2801 Use Named.of to describe parameterized tests input
  reactor-core/src/test/java/reactor/core/publisher/FluxDoOnEachTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxUsingWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheTimeTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/util/concurrent/QueuesTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/scheduler/SchedulersMetricsTest.java
Labels: type/chores

#2776 Bump ByteBuddy to 1.11.16, use TestKit in agent integration test
  build.gradle
  reactor-tools/build.gradle
  reactor-tools/src/buildPluginTest/java/reactor/tools/agent/ApplyingByteBuddyPluginGradleTest.java
  reactor-tools/src/buildPluginTest/resources/mock-gradle/build.gradle
  reactor-tools/src/buildPluginTest/resources/mock-gradle/settings.gradle
  reactor-tools/src/buildPluginTest/resources/mock-gradle/src/main/java/demo/SomeClass.java
  reactor-tools/src/buildPluginTest/resources/mock-gradle/src/test/java/demo/SomeClassTest.java
Labels: type/enhancement, type/chores
