Repository reactor/reactor-core, pull requests merged in 2021-04, with the labels that each got.

#2668 Remove Fuseable from MonoSingle[Mono|Callable]
  reactor-core/src/main/java/reactor/core/publisher/MonoSingleCallable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingleMono.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleCallableTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleMonoTest.java
Labels: type/bug

#2666 Remove jcenter() from build, update jcstress plugin to 0.8.8
  build.gradle
  buildSrc/build.gradle
  docs/asciidoc/kotlin.adoc
  gradle/asciidoc.gradle
  reactor-core/build.gradle
  reactor-test/build.gradle
Labels: type/chores

#2670 GitHub Actions Release Process: signing, artifactory, sonatype
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  gradle/releaser.gradle
  gradle/setup.gradle
  reactor-core/build.gradle
Labels: type/chores

#2676 Prevent infinite recursion of MonoMaterialize#request
  reactor-core/src/main/java/reactor/core/publisher/MonoMaterialize.java
  reactor-core/src/test/java/reactor/core/publisher/MonoMaterializeTest.java
Labels: type/bug

#2681 GroupBy request 1 more group when last active group is cancelled
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
Labels: type/bug

#2679 Renamed default branch to `main`, update CI
  .github/workflows/publish.yml
  README.md
  docs/asciidoc/aboutDoc.adoc
  docs/asciidoc/gettingStarted.adoc
  docs/asciidoc/highlight/CHANGES.md
  docs/asciidoc/highlight/README.md
  docs/asciidoc/highlight/README.ru.md
  docs/asciidoc/index.asciidoc
  docs/asciidoc/processors.adoc
  docs/asciidoc/testing.adoc
Labels: type/chores

#2685 Use `contextWrite(f)` rather than subscriberContext(f) in docs
  docs/asciidoc/advancedFeatures.adoc
Labels: type/documentation
