Repository reactor/reactor-core, pull requests merged in 2021-02, with the labels that each got.

#2581 Fix a few return types in Mono javadocs
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation

#2566 Add hook to wrap Queues
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
  reactor-core/src/main/java/reactor/util/concurrent/Queues.java
  reactor-core/src/test/java/reactor/ReactorTestExecutionListener.java
  reactor-core/src/test/java/reactor/util/concurrent/QueuesTest.java
Labels: area/devexp, type/enhancement

#2590 [doc] Format Consumer<Subscription> in backpressure doc
  docs/asciidoc/subscribe-backpressure.adoc
Labels: type/documentation

#2592 Amend SerializedSubscriberTest to accept rare double discard
  reactor-core/src/test/java/reactor/core/publisher/SerializedSubscriberTest.java
Labels: type/enhancement

#2596 Provide a reworked FluxSwitchMap with no queue
  reactor-core/build.gradle
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchMapStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscriber.java
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscription.java
  reactor-core/src/jcstress/resources/logback.xml
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchMapNoPrefetch.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchMapTest.java
Labels: type/enhancement, warn/deprecation

#2612 Polish after #2576: ScalarSubscription scanUnsafe
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/test/java/reactor/core/publisher/FluxJustTest.java
  reactor-core/src/test/java/reactor/core/publisher/OperatorsTest.java
Labels: type/enhancement

#2613 Polish after #2576: ScalarSubscription has RunStyle.SYNC
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
Labels: type/chores

#2617 Fix wrong param name in Sinks.Many#limit(Duration) javadoc
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
Labels: type/documentation

#2621 Remove CustomVersionPlugin
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/io/reactor/gradle/CustomVersionPlugin.java
  buildSrc/src/test/java/io/reactor/gradle/CustomVersionPluginTest.java
Labels: type/chores
