Repository reactor/reactor-core, pull requests merged in 2021-11, with the labels that each got.

#2825 [agent] Bump OpCode to ASM9 for compatibility with newer JDKs
  reactor-tools/src/main/java/reactor/tools/agent/CallSiteInfoAddingMethodVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ReactorDebugClassVisitor.java
  reactor-tools/src/main/java/reactor/tools/agent/ReturnHandlingMethodVisitor.java
Labels: type/bug, type/chores, area/java9

#2820 Improve traceback rendering of checkpoints
  reactor-core/src/main/java/reactor/core/publisher/ConnectableFluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxCallableOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCallableOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/MonoOnAssembly.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFluxOnAssembly.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
Labels: type/enhancement, area/devexp

#2828 Use gradle-build-action for invoking Gradle on CI
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: type/chores

#2823 Add logging convenience methods, polish a few messages
  reactor-core/src/main/java/reactor/core/publisher/FluxMetrics.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheInvalidateWhen.java
  reactor-core/src/main/java/reactor/util/Logger.java
  reactor-core/src/test/java/reactor/util/LoggerTest.java
Labels: type/enhancement

#2833 Make OnAssemblyException serializable again
  reactor-core/src/main/java/reactor/core/publisher/FluxOnAssembly.java
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
Labels: type/enhancement

#2834 Fix flatMapMany description typo
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation
