Repository reactor/reactor-core, pull requests merged in 2021-07, with the labels that each got.

#2738 [polish] Tag 3min worth of tests as 'slow'
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferPredicateTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTakeTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCollectListTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCompletionStageTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoIgnoreThenTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/core/publisher/ParallelFluxTest.java
  reactor-core/src/test/java/reactor/core/publisher/QueueDrainSubscriberTest.java
  reactor-core/src/test/java/reactor/core/publisher/SerializedSubscriberTest.java
  reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
  reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersHooksTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
Labels: type/chores

#2737 Have groupBy replenish prefetch amount when last inner cancels
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
Labels: area/performance, type/enhancement

#2717 Add Mono.cacheInvalidate[If|When]
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheInvalidateIf.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheInvalidateWhen.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheInvalidateIfTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheInvalidateWhenTest.java
  reactor-core/src/test/java/reactor/test/MemoryUtils.java
Labels: for/fast-track, for/team-attention, type/enhancement

#2746 Clarify behavior of collect* operators on empty sequences
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/documentation

#2749 Fix hanging of windoUntil(cutBefore=false) by replenishing
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowPredicate.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowPredicateTest.java
Labels: type/bug
