Repository reactor/reactor-core, pull requests merged in 2021-03, with the labels that each got.

#2625 Fix Mono.publish(Function) not propagating onError
  reactor-core/src/main/java/reactor/core/publisher/MonoPublishMulticast.java
  reactor-core/src/test/java/reactor/core/publisher/MonoPublishMulticastTest.java
Labels: type/bug

#2627 Add a RaceTestUtils.race variant with timeout parameter
  reactor-test/src/main/java/reactor/test/util/RaceTestUtils.java
Labels: type/enhancement

#2628 Fix flatMap race favoring onComplete over onError
  reactor-core/src/main/java/reactor/core/publisher/FluxFlatMap.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java
Labels: type/bug

#2622 Fix Sinks.unsafe() snippet in advancedFeatures.adoc
  docs/asciidoc/advancedFeatures.adoc
Labels: type/documentation

#2631 Prevent ordered merge hanging due to badly sized queue
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxMergeOrdered.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelMergeOrdered.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeOrderedTest.java
  reactor-core/src/test/java/reactor/core/publisher/ParallelMergeOrderedTest.java
Labels: type/bug

#2645 improves `MonoProducerBase` and removes `Fusion` from MonoSingle
  reactor-core/src/jcstress/java/reactor/core/publisher/MonoInnerProducerBaseStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingle.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
Labels: type/enhancement

#2648 ensures `Mono#single` works in `Callable` fusion scenario
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingleCallable.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleTest.java
Labels: type/bug

#2650 Polish comments format in build.gradle
  build.gradle
  reactor-core/build.gradle
  reactor-test/build.gradle
  reactor-tools/build.gradle
Labels: type/chores

#2652 Account for source disconnection in refCountGrace
  reactor-core/src/main/java/reactor/core/publisher/FluxRefCountGrace.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java
Labels: type/bug

#2655 Avoid infinite discard loop on fused fromIterable/fromStream
  reactor-core/src/main/java/reactor/core/publisher/FluxIterable.java
  reactor-core/src/test/java/reactor/core/publisher/FluxIterableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxStreamTest.java
Labels: type/bug

#2658 Fix buffer ctor error message displaying wrong variable name
  reactor-core/src/main/java/reactor/core/publisher/FluxBuffer.java
Labels: type/enhancement

#2657 Fix both `Flux.single` variants when applied to a `Callable`
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingleCallable.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleCallableTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleTest.java
Labels: type/bug

#2604 Make Mono.then execution model more deterministic
  reactor-core/src/main/java/reactor/core/publisher/MonoIgnoreThen.java
  reactor-core/src/test/java/reactor/core/publisher/MonoThenIgnoreTest.java
Labels: type/enhancement

#2659 Polish MonoSingleCallableTest and MonoThenIgnoreTest
  reactor-core/src/test/java/reactor/core/publisher/MonoIgnoreThenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleCallableTest.java
Labels: type/chores

#2662 Clarify onErrorContinue() caveats and alternatives
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation
