Repository reactor/reactor-core, pull requests merged in 2022-11, with the labels that each got.

#3256 Context propagation: use new APIs from latest snapshots
  gradle/libs.versions.toml
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/FluxHandle.java
  reactor-core/src/main/java/reactor/core/publisher/FluxHandleFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoHandle.java
  reactor-core/src/main/java/reactor/core/publisher/MonoHandleFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTap.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTapFuseable.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/enhancement, area/context, area/observability

#3260 fixes incorrect value/error set during `tryEmitXXX` call
  reactor-core/src/jcstress/java/reactor/core/publisher/SinkOneStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/SinkEmptyMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/SinkOneMulticast.java
Labels: type/bug

#3262 cleans context for concat map for retry companion publisher
  reactor-core/src/main/java/reactor/util/retry/RetryBackoffSpec.java
  reactor-core/src/main/java/reactor/util/retry/RetrySpec.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
Labels: type/bug

#3271 Document usage of the EmitFailureHandler.busyLooping in refguide
  docs/asciidoc/processors.adoc
Labels: type/documentation

#3263 Only initialize logging once per test session
  reactor-core/src/test/java/reactor/ReactorLauncherSessionListener.java
  reactor-core/src/test/java/reactor/ReactorTestExecutionListener.java
  reactor-core/src/test/java/reactor/util/LoggersTest.java
  reactor-core/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener
Labels: type/enhancement

#3259 Limit the number of Scheduler#disposeGracefully threads
  reactor-core/build.gradle
  reactor-core/src/jcstress/java/reactor/core/scheduler/BasicSchedulersStressTest.java
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/SchedulerState.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
Labels: type/enhancement

#3272 Improve Mono fromFuture/fromCompletionStage javadocs
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation

#3274 Upgrade Micrometer/Context-Propagation dependencies to 1.10.0 GA
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3279 Revert "Add jcenter() to the repositories list"
  build.gradle
Labels: type/chores

#3287 Fix regression: Sinks.one()#tryEmitValue(null)
  reactor-core/src/main/java/reactor/core/publisher/SinkOneMulticast.java
  reactor-core/src/test/java/reactor/core/publisher/SinkOneMulticastTest.java
Labels: type/bug, warn/regression
