Repository reactor/reactor-core, pull requests merged in 2022-10, with the labels that each got.

#3203 Ensure StepVerifier evaluates signal that exits thenConsumeWhile
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
  reactor-test/src/test/java/reactor/test/DefaultStepVerifierBuilderTests.java
Labels: for/user-attention

#3215 Adapt to Micrometer SNAPSHOTs before RC1
  gradle/asciidoc.gradle
  gradle/libs.versions.toml
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/Micrometer.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListener.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListenerDocumentation.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListenerConfiguration.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListenerDocumentation.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedScheduler.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedSchedulerMeterDocumentation.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java
  reactor-core/src/main/java/reactor/util/context/ReactorContextAccessor.java
  reactor-core/src/withMicrometerTest/java/reactor/util/context/ReactorContextAccessorTest.java
Labels: status/on-hold, type/chores, type/dependency-upgrade

#3217 Fix meters documentation generation following renames
  docs/asciidoc/metrics-details.adoc
  gradle/asciidoc.gradle
Labels: type/documentation, type/chores, warn/blocker, area/observability

#3145 Add ContextPropagation runtime util + captureContext operator
  docs/asciidoc/advanced-contextPropagation.adoc
  docs/asciidoc/advancedFeatures.adoc
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/ContextPropagationNotThereSmokeTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/enhancement, area/observability

#3218 Update dependencies junit, mockito, bytebuddy, jcstress, spotless...
  gradle/libs.versions.toml
  reactor-tools/src/buildPluginTest/resources/mock-gradle/build.gradle
Labels: type/dependency-upgrade

#3220 Micrometer Observation test: ensure assert fails the test
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationIntegrationTest.java
Labels: type/chores

#3225 Polish Micrometer Docs generation
  gradle/asciidoc.gradle
  gradle/libs.versions.toml
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListenerDocumentation.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListenerDocumentation.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedSchedulerMeterDocumentation.java
Labels: type/documentation, area/observability

#3224 Document not to reuse/cache EmitFailureHandle#busyLooping
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
Labels: type/documentation

#3219 Fix cancel behavior of FluxTakeUntilOther
  reactor-core/src/main/java/reactor/core/publisher/FluxTakeUntilOther.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTakeUntilOtherTest.java
Labels: type/enhancement

#3221 Make use of CompletionStage#handle instead of `whenComplete`
  reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java
Labels: type/enhancement, area/performance

#3228 Update Micrometer dependency to RC1
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3205 Rework the refguide section on metrics to focus on new module
  docs/asciidoc/metrics-details.adoc
  docs/asciidoc/metrics.adoc
Labels: type/documentation, area/observability

#3241 Fix flaky FluxPublishOnTest
  reactor-core/src/test/java/reactor/core/publisher/FluxPublishOnTest.java
Labels: type/chores

#3236 Deprecate scheduler start
  reactor-core/src/blockHoundTest/java/reactor/core/scheduler/BoundedElasticSchedulerBlockhoundTest.java
  reactor-core/src/jcstress/java/reactor/core/scheduler/SchedulersStressTest.java
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ImmediateScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Scheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/core/scheduler/AbstractSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/DelegateServiceSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ElasticSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ExecutorSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ExecutorSchedulerTrampolineTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ImmediateSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ParallelSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleWorkerAroundTimerSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleWorkerSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/TimedSchedulerTest.java
  reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java
Labels: warn/deprecation

#3243 Scheduler.isDisposed() only true for disposed instances
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/test/java/reactor/core/scheduler/AbstractSchedulerTest.java
Labels: warn/behavior-change

#3209 adds on discard support for `FluxZip`/`MonoZip`
  reactor-core/src/main/java/reactor/core/publisher/FluxZip.java
  reactor-core/src/main/java/reactor/core/publisher/MonoZip.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFilterFuseableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxZipTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCacheInvalidateWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-test/src/main/java/reactor/test/publisher/DefaultTestPublisher.java
  reactor-test/src/main/java/reactor/test/publisher/TestPublisher.java
Labels: type/enhancement, area/doOnDiscard

#3246 Fix the way context-propagation is detected
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
Labels: type/bug

#3237 Use new gha API for setting output, latest core actions
  .github/workflows/ci.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/publish.yml
  gradle/setup.gradle
Labels: type/chores

#3248 Optimize Scheduler initialization
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
Labels: type/enhancement

#3249 Further improve detection of ContextPropagation (see #3246)
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java
Labels: type/bug

#3247 Minor polish on documentation
  docs/asciidoc/advancedFeatures.adoc
Labels: type/documentation

#3234 various minor cleanups
  README.md
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/chores

#3254 Upgrade several plugins and test dependencies
  gradle/libs.versions.toml
  settings.gradle
Labels: type/dependency-upgrade

#3251 Remove marker need for tap/handle context-propagation
  docs/asciidoc/advanced-contextPropagation.adoc
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/test/java/reactor/core/publisher/ContextPropagationNotThereSmokeTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/enhancement, area/context, area/observability

#3252 fixes breaking change for `fromFuture` source cancellation
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCompletionStageTest.java
Labels: type/enhancement, for/user-attention
