Repository reactor/reactor-core, pull requests merged in 2022-04, with the labels that each got.

#2996 Update gradle/gradle-build-action to v2.1.5
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: type/dependency-upgrade

#2998 Avoid FluxReplay buffer retaining/leaking with tiny TTL
  reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java
  reactor-core/src/test/java/reactor/core/publisher/FluxReplayTest.java
Labels: type/bug, area/performance

#3006 Switch to Micrometer 2 (snapshots) and adapt where needed
  .github/renovate.json
  gradle/libs.versions.toml
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java
Labels: type/enhancement, type/dependency-upgrade, area/observability

#3008 Update ByteBuddy to v1.12.9
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#2995 [doc] Polish Schedulers javadoc for common/cached instances
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
Labels: type/documentation

#3009 Increase landscape width of refguide content for readability
  docs/asciidoc/stylesheets/reactor.css
Labels: type/documentation

#3010 [test] Improve flaky BoundedElasticScheduler toString test
  reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java
Labels: type/chores

#3014 Micrometer reverted split of binders
  gradle/libs.versions.toml
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java
Labels: type/chores, warn/blocker

#3016 Switch Micrometer snapshots to 1.10.0-SNAPSHOT
  gradle/libs.versions.toml
Labels: status/on-hold, type/dependency-upgrade

#3013 Add 'tap', a generic side-effect/observability operator
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTap.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTapFuseable.java
  reactor-core/src/main/java/reactor/util/observability/DefaultSignalListener.java
  reactor-core/src/main/java/reactor/util/observability/SignalListener.java
  reactor-core/src/main/java/reactor/util/observability/SignalListenerFactory.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTapTest.java
Labels: type/enhancement

#3021 Add default contextView() implem to [Flux|Mono|Synchronous]Sink
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/FluxSink.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSink.java
  reactor-core/src/main/java/reactor/core/publisher/SynchronousSink.java
  reactor-core/src/test/java/reactor/core/ContextBestPracticesArchTest.java
Labels: type/enhancement

#3026 Backport: contextView() implem of [Flux|Mono|Synchronous]Sink
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/FluxSink.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSink.java
  reactor-core/src/main/java/reactor/core/publisher/SynchronousSink.java
  reactor-core/src/test/java/reactor/core/ContextBestPracticesArchTest.java
Labels: type/enhancement, type/chores

#3025 Upgrade to Micrometer 1.10.0-M1 for 3.5.0-M2
  gradle/libs.versions.toml
Labels: type/dependency-upgrade, area/observability

#3007 Polish README
  README.md
Labels: type/documentation

#3029 Fix a Many sink / EmitterProcessor subscriber disposal leak
  reactor-core/src/main/java/reactor/core/publisher/EmitterProcessor.java
  reactor-core/src/test/java/reactor/core/publisher/EmitterProcessorTest.java
Labels: type/bug

#3030 Upgrade Checkout action, Mockito, Spotless, Artifactory
  .github/workflows/ci.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/publish.yml
  gradle/libs.versions.toml
Labels: type/dependency-upgrade
