Repository reactor/reactor-core, pull requests merged in 2022-07, with the labels that each got.

#3098 Add context-propagation-api dependency + ReactorContextAccessor
  gradle/libs.versions.toml
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/util/context/ReactorContextAccessor.java
  reactor-core/src/main/resources/META-INF/services/io.micrometer.context.ContextAccessor
Labels: type/enhancement, type/dependency-upgrade, area/observability

#3097 Implement disposing of tasks scheduled on VirtualTimeScheduler
  reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java
  reactor-test/src/test/java/reactor/test/scheduler/VirtualTimeSchedulerTests.java
Labels: type/enhancement, area/reactor-test

#3101 Introducing default impl for Context::forEach
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/util/context/ContextView.java
Labels: type/enhancement, area/context

#3100 Make context-propagation-api dependency optional + documentation
  docs/asciidoc/advancedFeatures.adoc
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/util/context/ReactorContextAccessor.java
Labels: type/chores

#3102 Introducing Context::putAllMap
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/util/context/Context.java
  reactor-core/src/main/java/reactor/util/context/ContextN.java
  reactor-core/src/test/java/reactor/util/context/Context0Test.java
  reactor-core/src/test/java/reactor/util/context/Context1Test.java
  reactor-core/src/test/java/reactor/util/context/Context2Test.java
  reactor-core/src/test/java/reactor/util/context/Context3Test.java
  reactor-core/src/test/java/reactor/util/context/Context4Test.java
  reactor-core/src/test/java/reactor/util/context/Context5Test.java
  reactor-core/src/test/java/reactor/util/context/ContextNTest.java
  reactor-core/src/test/java/reactor/util/context/ContextTest.java
Labels: type/enhancement

#3093 Rework guide on Retry with Transient Errors
  docs/asciidoc/coreFeatures.adoc
  reactor-core/src/test/java/reactor/guide/GuideTests.java
Labels: type/documentation

#3104 Micrometer module: add observation(), deprecate global registry
  gradle/libs.versions.toml
  reactor-core-micrometer/build.gradle
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/Micrometer.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListener.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListenerConfiguration.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListenerFactory.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListenerConfiguration.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListenerFactory.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerMeterListenerConfigurationTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerMeterListenerFactoryTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerMeterListenerTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationIntegrationTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerConfigurationTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerFactoryTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerTest.java
  reactor-core/src/main/java/reactor/core/observability/SignalListener.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTap.java
Labels: type/enhancement, warn/deprecation, area/observability

#3113 Adapt to the changes in the context propagation API
  docs/asciidoc/advancedFeatures.adoc
  gradle/libs.versions.toml
  reactor-core-micrometer/build.gradle
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/Micrometer.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/util/context/ReactorContextAccessor.java
Labels: type/chores, type/dependency-upgrade

#3112 Reintroduction of Processors as deprecated
  reactor-core/src/main/java/reactor/core/publisher/DelegateProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/DirectInnerContainer.java
  reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/EmitterProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/FluxProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/MonoProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/NextProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/ReplayProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/SinkManyBestEffort.java
  reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java
Labels: type/chores, warn/blocker, for/team-attention

#3115 July dependency upgrades
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  gradle/libs.versions.toml
  settings.gradle
Labels: type/dependency-upgrade

#3116 Update Micrometer dependency to version 1.10.0-M3
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3119 Micrometer#observation(): avoids scopes, set parentObservation
  gradle/libs.versions.toml
  reactor-core-micrometer/build.gradle
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerTest.java
Labels: type/enhancement, type/dependency-upgrade, area/observability

#3124 Adapt to ContextAccessor change: new readValue method
  reactor-core/src/main/java/reactor/util/context/ReactorContextAccessor.java
  reactor-core/src/withMicrometerTest/java/reactor/util/context/ReactorContextAccessorTest.java
Labels: type/enhancement, warn/blocker, area/observability

#3127 Upgrade Gradle to 7.5, workaround nohttp, update gradle action
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  codequality/nohttp/checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type/dependency-upgrade

#3128 Remove Micrometer#useRegistry, remove notion of Clock
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/Micrometer.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListener.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListenerConfiguration.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerMeterListenerFactory.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerMeterListenerConfigurationTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerMeterListenerFactoryTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerMeterListenerTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerTest.java
Labels: type/enhancement, warn/api-change, area/observability

#3132 Fix a couple reactor-core-micrometer module compilation errors
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/Micrometer.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerConfigurationTest.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerFactoryTest.java
Labels: type/chores, warn/blocker, area/observability
