Repository reactor/reactor-core, pull requests merged in 2022-06, with the labels that each got.

#3047 Correct typo in metrics.adoc
  docs/asciidoc/metrics.adoc
Labels: type/documentation

#3053 Fix cancel too synchronized in MonoCollect[List]
  reactor-core/src/main/java/reactor/core/publisher/MonoCollect.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCollectList.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCollectListTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoCollectTest.java
Labels: type/bug

#3066 June dependency upgrades
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  gradle/libs.versions.toml
  reactor-core/src/test/java/reactor/core/QueueSubscriptionTest.java
  reactor-tools/src/buildPluginTest/resources/mock-gradle/build.gradle
  settings.gradle
Labels: type/dependency-upgrade

#3065 Rework Processor-with-upstream case to be backward compatible
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/EmitterProcessor.java
  reactor-core/src/main/java/reactor/core/publisher/Sinks.java
  reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java
  reactor-core/src/test/java/reactor/core/publisher/EmitterProcessorTest.java
Labels: type/enhancement

#3046 Async fusion bug: extra fixes and changes
  reactor-core/src/blockHoundTest/java/reactor/core/scheduler/ReactorBlockHoundIntegrationTest.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoFinally.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDoFinallyFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDoFinally.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDoFinallyFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoPeekTerminal.java
  reactor-core/src/test/java/reactor/core/publisher/FluxDoFinallyTest.java
  reactor-core/src/test/java/reactor/core/publisher/FuseableBestPracticesArchTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoDoFinallyTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoPeekAfterTest.java
  reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java
Labels: type/bug

#3070 Update plugin bnd to v6.3.1
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3069 Introducing JCStress tests for concurrent queues
  reactor-core/src/jcstress/java/reactor/util/concurrent/MpscLinkedQueueStressTest.java
  reactor-core/src/jcstress/java/reactor/util/concurrent/SpscArrayQueueStressTest.java
  reactor-core/src/jcstress/java/reactor/util/concurrent/SpscLinkedArrayQueueStressTest.java
Labels: type/chores

#3054 Implement variant of windowTimeout with fairBackpressure
  reactor-core/build.gradle
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxWindowTimeoutStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/InnerStressSubscriber.java
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscriber.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowTimeout.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowTimeoutTest.java
  reactor-test/src/main/java/reactor/test/util/RaceTestUtils.java
Labels: type/bug, type/enhancement

#3074 Fix windowTimeout stress test to use sinks
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxWindowTimeoutStressTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxWindowTimeoutTest.java
Labels: type/enhancement

#3075 Fix doc typo: missing word in reactiveProgramming.adoc
  docs/asciidoc/reactiveProgramming.adoc
Labels: type/documentation

#3073 Add windowTimeout sendNext early guard against maxSize overflow
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowTimeout.java
Labels: type/enhancement

#3077 Add StateLogger for structured logging of state machines
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchMapStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchOnFirstConditionalStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchOnFirstStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxWindowTimeoutStressTest.java
  reactor-core/src/jcstress/java/reactor/core/util/FastLogger.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchMapNoPrefetch.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/StateLogger.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchMapTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchOnFirstTest.java
Labels: type/enhancement, area/performance
