Repository reactor/reactor-core, pull requests merged in 2022-01, with the labels that each got.

#2871 [docs] Fix log output descriptions in faq docs
  docs/asciidoc/faq.adoc
Labels: type/documentation

#2869 [doc] Fix several small typos in Flux javadocs
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/documentation

#2859 UsingWhen leak / fails to cancel when early cancel race
  reactor-core/src/jcstress/java/reactor/core/publisher/MonoUsingWhenStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxUsingWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoUsingWhen.java
  reactor-core/src/test/java/reactor/core/publisher/MonoUsingWhenTest.java
Labels: type/bug, area/doOnDiscard

#2872 Automatically draft release notes on maintenance branches push
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  gradle/setup.gradle
Labels: type/chores

#2876 Fix draft release note generation for multiple branches/drafts
  .github/drafter-config.json
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  gradle/setup.gradle
Labels: type/chores

#2877 Update JmhExecTask to use latest Gradle task APIs
  buildSrc/src/main/java/io/reactor/gradle/JmhExecTask.java
Labels: type/chores

#2887 Replace drafter workflow with github's simple generator config
  .github/drafter-config.json
  .github/release.yml
  .github/workflows/release-drafter.yml
  gradle/setup.gradle
Labels: type/chores

#2888 Renovate group patched libs only, separate all plugin updates
  .github/renovate.json
Labels: type/chores, type/dependency-upgrade

#2884 Fix Flux.generate request accounting leading to hanging
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxGenerateStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxGenerate.java
Labels: type/bug

#2896 [doc] Consistently use replaySink var name for sink example
  docs/asciidoc/processors.adoc
Labels: type/documentation

#2893 Rewrite a MonoSubscribeOn test to be less flaky
  reactor-core/src/test/java/reactor/core/publisher/MonoSubscribeOnTest.java
Labels: type/chores

#2895 Run preliminary spotless/japicmp job in ci, fix japicmp of core
  .github/workflows/ci.yml
  reactor-core/build.gradle
Labels: type/chores

#2901 [build] Action updates: fix pinning
  .github/renovate.json
Labels: type/chores
