Repository reactor/reactor-core, pull requests merged in 2023-03, with the labels that each got.

#3374 Exclude `ContextPropagation#isContextPropagationAvailable` from the preprocessing for `native-image` support
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
Labels: type/enhancement

#3377 Replace Renovate with Dependabot
  .github/dependabot.yml
  .github/renovate.json
  benchmarks/build.gradle
  build.gradle
  buildSrc/build.gradle
  gradle/dependencies.gradle
  gradle/libs.versions.toml
  reactor-core/build.gradle
  reactor-test/build.gradle
  reactor-tools/build.gradle
Labels: type/chores

#3381 Apply dependencies.gradle in root project
  build.gradle
Labels: type/chores

#3385 Dependabot: ignore Mockito 5.x
  .github/dependabot.yml
Labels: type/chores

#3392 Dependabot: improve ignored versions spec
  .github/dependabot.yml
Labels: type/chores

#3409 Remove Fuseable interface from ContextWriteRestoringThreadLocals
  reactor-core/src/main/java/reactor/core/publisher/FluxContextWriteRestoringThreadLocals.java
  reactor-core/src/main/java/reactor/core/publisher/MonoContextWriteRestoringThreadLocals.java
Labels: type/enhancement, area/context
