Repository reactor/reactor-core, pull requests merged in 2023-10, with the labels that each got.

#3566 dedicated loom oriented boundeElasticScheduler implementation
  gradle/toolchains.gradle
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/ThreadPerTaskBoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/VirtualThreadFactory.java
  reactor-core/src/main/java21/reactor/core/scheduler/BoundedElasticSchedulerSupplier.java
  reactor-core/src/main/java21/reactor/core/scheduler/ThreadPerTaskBoundedElasticScheduler.java
  reactor-core/src/main/java21/reactor/core/scheduler/VirtualThreadFactory.java
  reactor-core/src/test/java/reactor/core/scheduler/BoundedElasticSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/GenericThreadPerTaskBoundedElasticSchedulerTest.java
  reactor-core/src/test/java21/reactor/core/scheduler/ThreadPerTaskBoundedElasticSchedulerTest.java
  reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java
Labels: type/enhancement, area/loom

#3597 improves build speed
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  reactor-core/build.gradle
Labels: type/chores

#3609 Handling 1.0.0 of context-propagation
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagationSupport.java
Labels: area/context

#3610 ensures `addCap` always returns value with flag
  reactor-core/src/main/java/reactor/core/publisher/FluxCreate.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCreateTest.java
Labels: type/bug, warn/regression

#3611 provides extra check for contextualName presence
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java
Labels: type/enhancement, area/observability

#3614 ensures that proper index is used during onNext check
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferTimeout.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutTest.java
Labels: type/bug

#3623 ensures SchedulerTask uses isShutdown instead of isDisposed
  reactor-core/src/main/java21/reactor/core/scheduler/ThreadPerTaskBoundedElasticScheduler.java
Labels: type/bug

#3617 Revised documentation about context propagation
  docs/asciidoc/advanced-contextPropagation.adoc
  docs/asciidoc/advancedFeatures.adoc
  docs/asciidoc/coreFeatures.adoc
Labels: type/documentation, area/context

#3625 InternalOperator automatic context propagation
  reactor-core/src/main/java/reactor/core/publisher/ConnectableLift.java
  reactor-core/src/main/java/reactor/core/publisher/ConnectableLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferBoundary.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatMap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatMapNoPrefetch.java
  reactor-core/src/main/java/reactor/core/publisher/FluxDelaySubscription.java
  reactor-core/src/main/java/reactor/core/publisher/FluxExpand.java
  reactor-core/src/main/java/reactor/core/publisher/FluxFilterWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupJoin.java
  reactor-core/src/main/java/reactor/core/publisher/FluxJoin.java
  reactor-core/src/main/java/reactor/core/publisher/FluxLift.java
  reactor-core/src/main/java/reactor/core/publisher/FluxLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxMergeSequential.java
  reactor-core/src/main/java/reactor/core/publisher/FluxOnErrorResume.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublishMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRepeatWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRetry.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSample.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSampleFirst.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSampleTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSkipUntilOther.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchIfEmpty.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchMap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSwitchMapNoPrefetch.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTakeUntilOther.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowBoundary.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWindowWhen.java
  reactor-core/src/main/java/reactor/core/publisher/FluxWithLatestFrom.java
  reactor-core/src/main/java/reactor/core/publisher/GroupedLift.java
  reactor-core/src/main/java/reactor/core/publisher/GroupedLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheInvalidateWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDelaySubscription.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFilterWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFlatMap.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFlatMapMany.java
  reactor-core/src/main/java/reactor/core/publisher/MonoLift.java
  reactor-core/src/main/java/reactor/core/publisher/MonoLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoPublishMulticast.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSwitchIfEmpty.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTakeUntilOther.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelLift.java
  reactor-core/src/main/java/reactor/core/publisher/ParallelLiftFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/SignalLogger.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/AutomaticContextPropagationTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ThreadSwitchingFlux.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ThreadSwitchingMono.java
Labels: area/context
