Repository reactor/reactor-core, pull requests merged in 2023-11, with the labels that each got.

#3630 JCStress: Await Scheduler dispose and increase timeouts
  reactor-core/src/jcstress/java/reactor/core/scheduler/BasicSchedulersStressTest.java
Labels: type/enhancement

#3631 updates to java 21 GA temurin
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
Labels: type/chores

#3632 Gradle 8.4 upgrade
  gradle/asciidoc.gradle
  gradle/javadoc.gradle
  gradle/releaser.gradle
  gradle/setup.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  reactor-core/build.gradle
  reactor-test/build.gradle
  reactor-tools/build.gradle
Labels: type/chores

#3637 Update micrometer, micrometerTracing, contextPropagation
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3638 makes `throwable` assignment happens-before `done` assignment in `onError` for FluxPublish
  reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java
Labels: type/bug, warn/regression

#3635 Improves documentation for VirtualThreads boundedElastic behavior
  docs/asciidoc/coreFeatures.adoc
  docs/asciidoc/faq.adoc
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticSchedulerSupplier.java
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticThreadPerTaskScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/VirtualThreadFactory.java
  reactor-core/src/main/java21/reactor/core/scheduler/BoundedElasticSchedulerSupplier.java
  reactor-core/src/main/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskScheduler.java
  reactor-core/src/main/java21/reactor/core/scheduler/VirtualThreadFactory.java
  reactor-core/src/test/java/reactor/core/scheduler/GenericBoundedElasticThreadPerTaskSchedulerTest.java
  reactor-core/src/test/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskSchedulerTest.java
Labels: type/documentation

#3643 StressSubscriber discardedValues should not have downstream type
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscriber.java
Labels: type/chores

#3646 Add test label to release notes template
  .github/release.yml
Labels: type/chores

#3328 MemoryUtils.Tracked used in tests releases collections
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/test/MemoryUtils.java
Labels: area/doOnDiscard, type/test
