Repository reactor/reactor-core, pull requests merged in 2023-08, with the labels that each got.

#3546 fixes MonoDelayElemnt to properly handle race between run and onNext
  reactor-core/src/jcstress/java/reactor/core/publisher/MonoDelayElementStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/MonoDelayElement.java
Labels: type/bug

#3544 fix reactor#3539 takeUntil Predicate test before emit
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTakeUntil.java
  reactor-core/src/test/java/reactor/core/publisher/FluxTakeUntilPredicateTest.java
Labels: type/bug

#3555 ensures `GroupedFlux` delivers subscription for the second subscriber
  reactor-core/src/main/java/reactor/core/publisher/FluxGroupBy.java
  reactor-core/src/test/java/reactor/core/publisher/FluxGroupByTest.java
Labels: type/bug

#3538 Reworks FluxPublish internals to relay on predictable state machine
  benchmarks/src/main/java/reactor/core/publisher/FluxPublishBenchmark.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxPublishStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
Labels: type/enhancement

#3557 ensures late `onRequest` consumer observes demand
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxCreateStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxCreate.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSink.java
  reactor-core/src/test/java/reactor/core/publisher/FluxCreateTest.java
Labels: type/bug

#3560 Update `Micrometer` version to `1.10.10`
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3561 upgrades to latest micrometer versions
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3564 Fix return type for Mono.tap in javadoc
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/documentation
