Repository reactor/reactor-core, pull requests merged in 2023-01, with the labels that each got.

#3325 Add reflection hints for native-image support
  reactor-core/src/main/resources/META-INF/native-image/io.projectreactor/reactor-core/reflect-config.json
Labels: type/bug

#3329 ensures empty inner handled properly in case of sync fusion
  reactor-core/src/main/java/reactor/core/publisher/FluxFlattenIterable.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlattenIterableTest.java
Labels: type/bug, warn/regression

#3317 Add .singleOptional() to Mono and Flux
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingleOptional.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSingleOptionalCallable.java
  reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/singleOptional.svg
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleMonoTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleOptionalCallableTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoSingleOptionalTest.java
Labels: type/enhancement
