Repository reactor/reactor-core, pull requests merged in 2023-04, with the labels that each got.

#3418 Propagate ThreadLocals for non-Reactor upstream sources
  reactor-core/src/main/java/reactor/core/publisher/FluxSource.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFromPublisher.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSource.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/enhancement, area/context, area/observability

#3397 makes error handling for fmSequential consistent with flatMap
  reactor-core/src/main/java/reactor/core/publisher/FluxMergeSequential.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeSequentialTest.java
Labels: type/enhancement

#3415 ensures SignalListener#addToContext exceptions are handled
  reactor-core/src/main/java/reactor/core/publisher/FluxTap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTap.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTapFuseable.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/FluxTapTest.java
Labels: type/bug, area/context

#3431 updates micrometer lib version
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3432 updates gradle version to 7.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: type/dependency-upgrade
