Repository reactor/reactor-core, pull requests merged in 2023-12, with the labels that each got.

#3664 Add test label to release notes template for < 3.6
  .github/release.yml
Labels: type/chores, ignore-changelog

#3665 ensure error is not propagated on cancellation and onNext race
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxPublishOnStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublishOn.java
Labels: type/bug

#3660 Fix pendingTask count not tracking task rejection
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedScheduler.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/TimedSchedulerTest.java
Labels: type/bug, area/observability

#3657 Fix typo in code sample
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
Labels: type/chores

#3670 Remove unintended dependency on gradle enterprise plugin
  gradle/toolchains.gradle
Labels: type/chores, ignore-changelog

#3669 Fix flaky test for pending tasks count validation
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/TimedSchedulerTest.java
Labels: type/test, type/test/flaky
