Repository reactor/reactor-core, pull requests merged in 2023-07, with the labels that each got.

#3521 adds support for gradle 8.1.1
  build.gradle
  buildSrc/settings.gradle
  gradle/dependencies.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  reactor-core/build.gradle
  reactor-tools/build.gradle
  settings.gradle
Labels: type/enhancement

#3517 enforces ordering on concurrent subscription to `FluxRefCount`
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxPublishStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRefCount.java
  reactor-core/src/main/java/reactor/core/publisher/FluxRefCountGrace.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountGraceTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRefCountTest.java
Labels: type/bug

#3528 Move to micrometer snapshots
  gradle/libs.versions.toml
Labels: area/observability

#3518 ensures `sourceMode` is obtained with happens-before relationships
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxPublishStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxPublish.java
Labels: type/bug

#3523 adds support for multi-release-jar | rework `Traces`
  .github/setup.sh
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .sdkmanrc
  build.gradle
  gradle/libs.versions.toml
  gradle/toolchains.gradle
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/publisher/CallSiteSupplierFactory.java
  reactor-core/src/main/java/reactor/core/publisher/Traces.java
  reactor-core/src/main/java8stubs/sun/misc/JavaLangAccess.java
  reactor-core/src/main/java8stubs/sun/misc/SharedSecrets.java
  reactor-core/src/main/java9/reactor/core/publisher/CallSiteSupplierFactory.java
  reactor-core/src/main/java9stubs/java/lang/StackWalker.java
  reactor-core/src/test/java/reactor/util/LoggerTest.java
  settings.gradle
Labels: type/enhancement

#3456 Issue #3455: ability to customize micrometer observation
  docs/asciidoc/metrics-details.adoc
  docs/asciidoc/metrics.adoc
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/Micrometer.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListenerFactory.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java
Labels: type/enhancement

#3524 introduces automatic loom support
  .github/workflows/ci.yml
  reactor-core/build.gradle
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticSchedulerSupplier.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java21/reactor/core/scheduler/BoundedElasticSchedulerSupplier.java
  reactor-core/src/test/java/reactor/core/publisher/ParallelFluxTest.java
Labels: type/enhancement, area/loom

#3533 fixes flaky test by ensuring CDL is awaited
  reactor-core/src/test/java/reactor/core/publisher/FluxFilterFuseableTest.java
Labels: type/enhancement

#3516 Add tests for context values with scope semantics
  reactor-core/src/withMicrometerTest/java/io/micrometer/scopedvalue/Scope.java
  reactor-core/src/withMicrometerTest/java/io/micrometer/scopedvalue/ScopeHolder.java
  reactor-core/src/withMicrometerTest/java/io/micrometer/scopedvalue/ScopedValue.java
  reactor-core/src/withMicrometerTest/java/io/micrometer/scopedvalue/ScopedValueThreadLocalAccessor.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationWithScopesTest.java
Labels: area/context

#3534 Extracted automatic context propagation tests to another class
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/AutomaticContextPropagationTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/enhancement, area/context
