Repository reactor/reactor-core, pull requests merged in 2023-05, with the labels that each got.

#3453 Update `Micrometer` version to `1.10.7`
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3459 Avoid IllegalStateException: Cannot resolve type description for io.micrometer.context.ContextRegistry
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagationSupport.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxHandle.java
  reactor-core/src/main/java/reactor/core/publisher/FluxHandleFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxSource.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTap.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFromPublisher.java
  reactor-core/src/main/java/reactor/core/publisher/MonoHandle.java
  reactor-core/src/main/java/reactor/core/publisher/MonoHandleFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/MonoSource.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTap.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTapFuseable.java
  reactor-core/src/test/java/reactor/core/publisher/ContextPropagationNotThereSmokeTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/bug

#3470 Remove redundant Operators.serialize in MonoTimeout#subscribeOrReturn
  reactor-core/src/main/java/reactor/core/publisher/MonoTimeout.java
Labels: type/enhancement

#3471 Add @Override to MonoDefer#subscribe
  reactor-core/src/main/java/reactor/core/publisher/MonoDefer.java
Labels: type/enhancement

#3448 Backport: [#3446] Optimize ContextN putAllInto
  reactor-core/src/main/java/reactor/util/context/ContextN.java
  reactor-core/src/test/java/reactor/util/context/ContextTest.java
Labels: type/enhancement

#3466 Improve documentation about subscribeOn
  docs/asciidoc/coreFeatures.adoc
  docs/asciidoc/faq.adoc
Labels: type/documentation

#3460 Allow null previous value
  gradle/libs.versions.toml
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
Labels: type/enhancement, area/context, area/observability
