Repository reactor/reactor-core, pull requests merged in 2023-02, with the labels that each got.

#3339 Remove Traces$SharedSecretsCallSiteSupplierFactory from the native-image configuration
  reactor-core/src/main/resources/META-INF/native-image/io.projectreactor/reactor-core/reflect-config.json
Labels: type/bug

#3337 Avoid BlockHound NoSuchTypeException when context propagation dependency is unavailable
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
Labels: type/enhancement

#3342 Upgrade gradle plugins
  gradle/libs.versions.toml
  settings.gradle
Labels: type/dependency-upgrade

#3343 Upgrade dependencies
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3344 Upgrade Micrometer dependencies
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3351 ensures exception is caught if inner fused for `FlatMap`
  reactor-core/src/main/java/reactor/core/publisher/FluxFlatMap.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlatMapTest.java
Labels: type/bug

#3335 Context propagation with automatic ThreadLocals restoration
  gradle/libs.versions.toml
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxContextWriteRestoringThreadLocals.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/Mono.java
  reactor-core/src/main/java/reactor/core/publisher/MonoContextWriteRestoringThreadLocals.java
  reactor-core/src/test/java/reactor/ReactorTestExecutionListener.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/FluxContextWriteRestoringThreadLocalsTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/MonoContextWriteRestoringThreadLocalsTest.java
Labels: type/enhancement, area/context, area/observability

#3356 ExecutorScheduler should use onScheduleHook
  reactor-core/src/main/java/reactor/core/scheduler/ExecutorScheduler.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulerWorkersHooksTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersHooksTest.java
Labels: type/bug, area/context

#3370 uses onErrorStop instead on cleaning context
  reactor-core/src/main/java/reactor/util/retry/RetryBackoffSpec.java
  reactor-core/src/main/java/reactor/util/retry/RetrySpec.java
Labels: type/bug

#3368 ContextQueue wrapper peek method implementation
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
Labels: type/bug, area/context, area/observability
