Repository reactor/reactor-core, pull requests merged in 2024-12, with the labels that each got.

#3945 Use maven scheme for ignored dependabot dependencies
  .github/dependabot.yml
Labels: type/chores

#3949 Polish #3901
  reactor-core/src/main/java/reactor/core/publisher/Traces.java
  reactor-core/src/test/java/reactor/core/publisher/TracesTest.java
Labels: type/enhancement, area/performance, area/observability

#3951 Update schedulers.adoc, Supplementary semicolon
  docs/modules/ROOT/pages/coreFeatures/schedulers.adoc
Labels: type/documentation
