Repository reactor/reactor-core, pull requests merged in 2024-05, with the labels that each got.

#3810 Bump Micrometer to v1.13.0
  gradle/libs.versions.toml
Labels: type/enhancement, area/observability

#3599 Fix "Blocking Mono Result" example
  README.md
Labels: type/documentation

#3817 Remove deprecations after #3816
  reactor-core/src/test/java/reactor/core/publisher/NextProcessorTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkEmptyMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/SinkOneMulticastTest.java
  reactor-core/src/test/java/reactor/core/publisher/UnicastManySinkNoBackpressureTest.java
Labels: type/test

#3819 Fail on missing asciidoctor pdf command
  README.md
  docs/build.gradle
Labels: type/documentation
