Repository reactor/reactor-core, pull requests merged in 2024-03, with the labels that each got.

#3676 Fix formatting in coreFeatures.adoc
  docs/asciidoc/coreFeatures.adoc
Labels: type/documentation

#3743 Bump `Micrometer` to version `1.12.4`
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3744 Bump `Micrometer Tracing` to version `1.2.4`
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3746 [build] Fix dependabot config
  .github/dependabot.yml
Labels: type/chores

#3748 [build] Use 'sanity' mode for JCStress for CI
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  reactor-core/build.gradle
Labels: type/chores

#3750 [build] Switch gradle-build-action to setup-gradle
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: type/dependency-upgrade

#3753 [build] Freeze Artifactory Gradle Plugin at 4.x
  .github/dependabot.yml
Labels: type/chores

#3757 [build] Correct actions/setup-gradle hash to 3.1.0
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: type/chores

#3758 [build] Migrate remaining gradle-build-action uses
  .github/workflows/nightly.yml
  .github/workflows/snapshots.yml
Labels: type/dependency-upgrade

#3761 Fix the remote branch used by spotless when running locally
  build.gradle
Labels: type/chores

#3763 [build] Include 3.6.x in github workflows
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  .github/workflows/snapshots.yml
Labels: type/chores

#3764 [build] Parallelize tests
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  gradle.properties
  reactor-core/build.gradle
  reactor-tools/build.gradle
Labels: type/chores

#3766 Observe more outcomes in DefaultTestSubscriberTest
  reactor-test/src/test/java/reactor/test/subscriber/DefaultTestSubscriberTest.java
Labels: type/test/flaky

#3767 [test] Ignore bufferTimeout discard validation
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
Labels: type/test/flaky

#3769 [build] Simplify ci.yml workflow
  .github/workflows/ci.yml
Labels: type/chores

#3770 [build] Simplify full.yml and snapshots.yml workflows
  .github/workflows/full.yml
  .github/workflows/snapshots.yml
Labels: type/chores

#3771 [build] Ignore type/test/flaky label in release notes
  .github/release.yml
Labels: type/chores
