Repository reactor/reactor-core, pull requests merged in 2024-08, with the labels that each got.

#3859 Fix ThreadPerTaskScheduler busyness accounting
  reactor-core/src/main/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskScheduler.java
  reactor-core/src/test/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskSchedulerTest.java
Labels: type/bug

#3861 [test] Disable asynchronicity in OnDiscard bufferTimeout test
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
Labels: type/test, type/test/flaky

#3862 [docs] Highlight Micrometer.observation vs Micrometer.metrics difference
  docs/modules/ROOT/pages/metrics.adoc
Labels: type/documentation, area/observability

#3874 [docs] Remove reference to missing type in Flux javadocs
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/documentation

#3872 [doc] Document when groupBy can deadlock because of backpressure
  docs/modules/ROOT/pages/advancedFeatures/advanced-three-sorts-batching.adoc
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
Labels: type/documentation

#3876 Call init() on delegate from TimedScheduler
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedScheduler.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/TimedSchedulerTest.java
Labels: type/bug, area/observability

#3822 [#3821] Fix `FluxBuffer` to request 1 when buffer is not modified
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBuffer.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferTest.java
Labels: status/need-user-input

#3883 Make Retry backoff multiplier configurable
  reactor-core/src/main/java/reactor/util/retry/Retry.java
  reactor-core/src/main/java/reactor/util/retry/RetryBackoffSpec.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
  reactor-core/src/test/java/reactor/util/retry/RetryBackoffSpecTest.java
Labels: type/enhancement
