Repository reactor/reactor-core, pull requests merged in 2024-04, with the labels that each got.

#3780 Fixes issue #3697 disposing TimedRunnable if disposed before scheduling
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedScheduler.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/TimedSchedulerTest.java
Labels: type/bug, area/observability

#3783 Remove Flux#thenMany optimization breaking concat
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxConcatArray.java
  reactor-core/src/test/java/reactor/core/publisher/FluxThenManyTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoThenManyTest.java
Labels: type/bug

#3779 #3772: wrapped with `await().untilAsserted`
  reactor-core/src/test/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskSchedulerTest.java
Labels: type/test/flaky

#3775 Corrected wrongly formatted words in faq.adoc
  docs/asciidoc/faq.adoc
Labels: type/documentation

#3790 Add `@Incubating` annotation
  reactor-core/src/main/java/reactor/util/annotation/Incubating.java
Labels: type/enhancement
