Repository reactor/reactor-core, pull requests merged in 2024-06, with the labels that each got.

#3634 BufferTimeout with fair backpressure rework
  benchmarks/src/main/java/reactor/core/publisher/FluxBufferTimeoutBenchmark.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxBufferTimeoutStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxBufferTimeout.java
  reactor-core/src/main/java/reactor/core/publisher/StateLogger.java
  reactor-core/src/test/java/reactor/core/publisher/FluxBufferTimeoutFairBackpressureTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
Labels: type/bug

#3818 Don't cleanup docs zip in case of build errors
  .github/workflows/publish.yml
Labels: type/documentation

#3824 Bump `Micrometer` to version `1.12.7`
  gradle/libs.versions.toml
  settings.gradle
Labels: type/enhancement

#3825 Bump `Micrometer` to version `1.13.1`
  gradle/libs.versions.toml
  settings.gradle
Labels: type/chores

#3707 Fix FluxReplay cancel and subscribe race between two Subscribers
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxReplayStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java
Labels: type/bug
