Repository reactor/reactor-core, pull requests merged in 2025-02, with the labels that each got.

#3973 Fix javaagent parameter syntax
  docs/modules/ROOT/pages/debugging.adoc
Labels: type/documentation

#3960 Support logging exception stack traces when the last argument is Throwable
  reactor-core/src/main/java/reactor/util/Loggers.java
  reactor-core/src/test/java/reactor/util/ConsoleLoggerTest.java
  reactor-core/src/test/java/reactor/util/JdkLoggerTest.java
Labels: type/enhancement

#3983 Upgrade shadow plugin to 8.3.6
  gradle/libs.versions.toml
  reactor-tools/build.gradle
Labels: type/dependency-upgrade

#3991 [build] Compile with recent javac but target JDK 8
  .github/workflows/ci.yml
  .github/workflows/full.yml
  .github/workflows/publish.yml
  .github/workflows/snapshots.yml
  build.gradle
  buildSrc/src/main/java/io/reactor/gradle/JavaConventions.java
  gradle/javadoc.gradle
  gradle/toolchains.gradle
Labels: type/chores

#3992 [build] Upgrade Gradle to 8.12.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type/chores

#3988 Switch to `ubuntu-22.04` runner
  .github/workflows/ci.yml
  .github/workflows/full.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/publish.yml
  .github/workflows/snapshots.yml
Labels: type/chores

#3993 [build] Update antora ubuntu runner to 22.04
  .github/workflows/publish.yml
Labels: type/chores

#3995 [build] Add CodeQL GitHub Action
  .github/workflows/codeql-analysis.yml
  README.md
Labels: type/chores

#3996 Bump Antora dependencies
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#3999 Bump junit version from 5.11.4 to 5.12.0
  gradle/dependencies.gradle
  reactor-test/build.gradle
  reactor-tools/src/buildPluginTest/resources/mock-gradle/build.gradle
Labels: type/chores

#4000 Publish milestones and release candidates to `Maven Central`
  .github/workflows/publish.yml
  README.md
  build.gradle
  docs/modules/ROOT/pages/gettingStarted.adoc
Labels: type/chores
