Repository reactor/reactor-core, pull requests merged in 2025-01, with the labels that each got.

#3975 Create dco.yml
  .github/dco.yml
Labels: type/chores

#3976 Prevent duplicate Observation.stop with Micrometer
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/MicrometerObservationListener.java
  reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java
Labels: type/bug, area/observability

#3978 Bump org.assertj:assertj-core from 3.26.3 to 3.27.3
  gradle/dependencies.gradle
  reactor-core/src/test/java/reactor/core/publisher/FluxOnAssemblyTest.java
Labels: type/dependency-upgrade

#3979 Interrupt VirtualThread task only from other Thread
  reactor-core/src/main/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskScheduler.java
  reactor-core/src/test/java21/reactor/core/scheduler/BoundedElasticThreadPerTaskSchedulerTest.java
Labels: type/bug
