Repository reactor/reactor-core, pull requests merged in 2025-03, with the labels that each got.

#4004 [test] Relax Flux#switchMap test2596 to avoid timeouts
  reactor-core/src/test/java/reactor/core/publisher/FluxSwitchMapTest.java
Labels: type/test/flaky

#4008 fix doc title displayed as untitled
  docs/modules/ROOT/pages/apdx-howtoReadMarbles.adoc
  docs/modules/ROOT/pages/apdx-operatorChoice.adoc
  docs/modules/ROOT/pages/apdx-reactorExtra.adoc
  docs/modules/ROOT/pages/faq.adoc
Labels: type/documentation

#4010 Depend on `Micrometer` `v1.12.13`
  gradle/libs.versions.toml
  settings.gradle
Labels: type/enhancement

#4009 Add more description on tap operator
  docs/modules/ROOT/pages/metrics.adoc
Labels: type/documentation

#4015 Eliminate most compiler warnings
  reactor-core-micrometer/src/main/java/reactor/core/observability/micrometer/TimedScheduler.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxBufferTimeoutStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/FluxSwitchMapStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/MonoDelayElementStressTest.java
  reactor-core/src/jcstress/java/reactor/core/publisher/StressSubscription.java
  reactor-core/src/jcstress/java/reactor/core/scheduler/BasicSchedulersStressTest.java
  reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java
  reactor-core/src/main/java/reactor/core/publisher/Flux.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapFuseable.java
  reactor-core/src/main/java/reactor/core/publisher/FluxTapRestoringThreadLocals.java
  reactor-core/src/main/java/reactor/core/publisher/Hooks.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheInvalidateIf.java
  reactor-core/src/main/java/reactor/core/publisher/MonoCacheInvalidateWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoFilterWhen.java
  reactor-core/src/main/java/reactor/core/publisher/MonoReduce.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTakeLastOne.java
  reactor-core/src/main/java/reactor/core/publisher/MonoTapRestoringThreadLocals.java
  reactor-core/src/main/java/reactor/core/publisher/Operators.java
  reactor-core/src/main/java/reactor/core/publisher/SinkManyBestEffort.java
  reactor-core/src/main/java/reactor/core/scheduler/BoundedElasticScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/ParallelScheduler.java
  reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java
  reactor-core/src/main/java/reactor/core/scheduler/SingleScheduler.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFilterFuseableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxFlattenIterableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxIterableTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxMergeOrderedTest.java
  reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/MonoFilterWhenTest.java
  reactor-core/src/test/java/reactor/core/publisher/OnDiscardShouldNotLeakTest.java
  reactor-core/src/test/java/reactor/core/scheduler/AbstractSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/ParallelSchedulerTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
  reactor-core/src/test/java/reactor/core/scheduler/SingleSchedulerTest.java
  reactor-core/src/withContextPropagation102Test/java/reactor/core/publisher/ContextPropagationTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/AutomaticContextPropagationTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/ContextPropagationWithScopesTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/FluxMetricsFuseableTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/FluxMetricsTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/MonoMetricsFuseableTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/publisher/MonoMetricsTest.java
  reactor-core/src/withMicrometerTest/java/reactor/core/scheduler/SchedulersMetricsTest.java
  reactor-core/src/withMicrometerTest/java/reactor/util/MetricsTest.java
  reactor-tools/src/jarFileTest/java/reactor/tools/JarFileShadingTest.java
Labels: type/chores
